<!-- Generated by ai2html on 2024-08-07 17:52 -->
<!-- ai file: millennials_flowchart.ai -->

<script>
  import { onMount } from "svelte";
  onMount(() => {
    (function (containerId, opts) {
      if (!("querySelector" in document)) return;
      var container = document.getElementById(containerId);
      var nameSpace = opts.namespace || "";
      var onResize = throttle(update, 200);
      var waiting = !!window.IntersectionObserver;
      var observer;
      update();

      document.addEventListener("DOMContentLoaded", update);
      window.addEventListener("resize", onResize);

      function update() {
        var artboards = selectChildren(
            "." + nameSpace + "artboard[data-min-width]",
            container
          ),
          width = Math.round(container.getBoundingClientRect().width);

        // Set artboard visibility based on container width
        artboards.forEach(function (el) {
          var minwidth = el.getAttribute("data-min-width"),
            maxwidth = el.getAttribute("data-max-width");
          if (+minwidth <= width && (+maxwidth >= width || maxwidth === null)) {
            if (!waiting) {
              selectChildren("." + nameSpace + "aiImg", el).forEach(
                updateImgSrc
              );
            }
            el.style.display = "block";
          } else {
            el.style.display = "none";
          }
        });

        // Initialize lazy loading on first call
        if (waiting && !observer) {
          if (elementInView(container)) {
            waiting = false;
            update();
          } else {
            observer = new IntersectionObserver(onIntersectionChange, {});
            observer.observe(container);
          }
        }
      }

      function elementInView(el) {
        var bounds = el.getBoundingClientRect();
        return bounds.top < window.innerHeight && bounds.bottom > 0;
      }

      // Replace blank placeholder image with actual image
      function updateImgSrc(img) {
        var src = img.getAttribute("data-src");
        if (src && img.getAttribute("src") != src) {
          img.setAttribute("src", src);
        }
      }

      function onIntersectionChange(entries) {
        // There may be multiple entries relating to the same container
        // (captured at different times)
        var isIntersecting = entries.reduce(function (memo, entry) {
          return memo || entry.isIntersecting;
        }, false);
        if (isIntersecting) {
          waiting = false;
          // update: don't remove -- we need the observer to trigger an update
          // when a hidden map becomes visible after user interaction
          // (e.g. when an accordion menu or tab opens)
          // observer.disconnect();
          // observer = null;
          update();
        }
      }

      function selectChildren(selector, parent) {
        return parent
          ? Array.prototype.slice.call(parent.querySelectorAll(selector))
          : [];
      }

      // based on underscore.js
      function throttle(func, wait) {
        var timeout = null,
          previous = 0;
        function run() {
          previous = Date.now();
          timeout = null;
          func();
        }
        return function () {
          var remaining = wait - (Date.now() - previous);
          if (remaining <= 0 || remaining > wait) {
            clearTimeout(timeout);
            run();
          } else if (!timeout) {
            timeout = setTimeout(run, remaining);
          }
        };
      }
    })("g-millennials_flowchart-box", {
      namespace: "g-",
      setup: window.setupInteractive || window.getComponent,
    });
  });
</script>

<div id="g-millennials_flowchart-box" class="ai2html">
  <!-- Artboard: app_fallback -->
  <div
    id="g-app_fallback"
    class="g-artboard"
    style="max-width: 300px;max-height: 1632px"
    data-aspect-ratio="0.184"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 543.9409% 0;"></div>
    <img
      id="g-app_fallback-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_flowchart/app_fallback.png?v=13"
    />
    <div
      id="_headline"
      class="g-shadow-text g-aiAbs"
      style="top:0.3677%;left:0%;width:100%;"
    >
      <p class="g-pstyle0">Headline</p>
    </div>
    <div
      id="_description"
      class="g-shadow-text g-aiAbs"
      style="top:1.6546%;left:0%;width:100%;"
    >
      <p class="g-pstyle1">
        Dek&mdash;Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        tempor
      </p>
    </div>
    <div
      id="g-ai0-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1643%;margin-top:-7.9px;left:43.3561%;width:93px;"
    >
      <p class="g-pstyle2">START HERE</p>
    </div>
    <div
      id="g-ai0-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:8.3265%;margin-top:-6.9px;left:36.3584%;width:135px;"
    >
      <p class="g-pstyle3">Graduates high school.</p>
    </div>
    <div
      id="g-ai0-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:10.3794%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2006</p>
      <p class="g-pstyle5">age 18</p>
    </div>
    <div
      id="g-ai0-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:11.6643%;margin-top:-11.3px;left:85.1911%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle6">Recieves</p>
      <p class="g-pstyle6">pre-college gift.</p>
    </div>
    <div
      id="g-ai0-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:13.3801%;margin-top:-11.3px;left:22.6745%;margin-left:-34.5px;width:69px;"
    >
      <p class="g-pstyle6">Works an</p>
      <p class="g-pstyle6">hourly job.</p>
    </div>
    <div
      id="g-ai0-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:13.5333%;margin-top:-5.8px;left:55.3164%;margin-left:-47px;width:94px;"
    >
      <p class="g-pstyle6">Goes to college.</p>
    </div>
    <div
      id="g-ai0-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.7534%;margin-top:-11.3px;left:55.3193%;margin-left:-45px;width:90px;"
    >
      <p class="g-pstyle6">Graduates with</p>
      <p class="g-pstyle6">bachelors.</p>
    </div>
    <div
      id="g-ai0-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:20.0904%;margin-top:-16.8px;left:85.112%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle6">Goes straight</p>
      <p class="g-pstyle6">to graduate</p>
      <p class="g-pstyle6">school.</p>
    </div>
    <div
      id="g-ai0-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:20.9811%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2010</p>
      <p class="g-pstyle5">age 22</p>
    </div>
    <div
      id="g-ai0-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:23.0013%;margin-top:-22.3px;left:37.0101%;margin-left:-38.5px;width:77px;"
    >
      <p class="g-pstyle6">Has debt.</p>
      <p class="g-pstyle6">Works a</p>
      <p class="g-pstyle6">full-time job</p>
      <p class="g-pstyle6">with 401k.</p>
    </div>
    <div
      id="g-ai0-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:22.511%;margin-top:-11.3px;left:59.2162%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle6">Freelancer.</p>
      <p class="g-pstyle6">Lives at home.</p>
    </div>
    <div
      id="g-ai0-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.6559%;margin-top:-22.3px;left:86.2936%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle6">Graduates with</p>
      <p class="g-pstyle6">masters. Works</p>
      <p class="g-pstyle6">full-time</p>
      <p class="g-pstyle6">with 401k.</p>
    </div>
    <div
      id="g-ai0-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.9623%;margin-top:-11.3px;left:59.2415%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle6">Moves out to</p>
      <p class="g-pstyle6">own apartment.</p>
    </div>
    <div
      id="g-ai0-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:26.4964%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2013</p>
      <p class="g-pstyle5">age 25</p>
    </div>
    <div
      id="g-ai0-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:28.7004%;margin-top:-22.3px;left:59.1628%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle6">Gets job with</p>
      <p class="g-pstyle6">401k. Doesn&rsquo;t</p>
      <p class="g-pstyle6">max out. Has</p>
      <p class="g-pstyle6">to help family.</p>
    </div>
    <div
      id="g-ai0-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:29.6196%;margin-top:-11.3px;left:85.2507%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle6">Buys home</p>
      <p class="g-pstyle6">with low rates.</p>
    </div>
    <div
      id="g-ai0-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:29.9894%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2015</p>
      <p class="g-pstyle5">age 27</p>
    </div>
    <div
      id="g-ai0-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:37.4024%;margin-top:-22.3px;left:85.2572%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle6">Loses job. Drains</p>
      <p class="g-pstyle6">investment</p>
      <p class="g-pstyle6">portfolio and</p>
      <p class="g-pstyle6">takes from 401k.</p>
    </div>
    <div
      id="g-ai0-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:37.77%;margin-top:-22.3px;left:59.2318%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle6">Goes</p>
      <p class="g-pstyle6">part-time to</p>
      <p class="g-pstyle6">help with</p>
      <p class="g-pstyle6">family care.</p>
    </div>
    <div
      id="g-ai0-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:39.059%;margin-top:-12.4px;left:0.2494%;width:56px;"
    >
      <p class="g-pstyle4">2020</p>
      <p class="g-pstyle5">age 32</p>
    </div>
    <div
      id="g-ai0-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:40.9873%;margin-top:-16.8px;left:22.0215%;margin-left:-37px;width:74px;"
    >
      <p class="g-pstyle6">Buys home</p>
      <p class="g-pstyle6">with low</p>
      <p class="g-pstyle6">rates.</p>
    </div>
    <div
      id="g-ai0-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:40.4971%;margin-top:-5.8px;left:85.1777%;margin-left:-47px;width:94px;"
    >
      <p class="g-pstyle6">Returns to work.</p>
    </div>
    <div
      id="g-ai0-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.5695%;margin-top:-11.3px;left:59.3451%;margin-left:-42.5px;width:85px;"
    >
      <p class="g-pstyle6">Returns to</p>
      <p class="g-pstyle6">work full-time.</p>
    </div>
    <div
      id="g-ai0-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:44.6335%;margin-top:-22.3px;left:59.2136%;margin-left:-43.5px;width:87px;"
    >
      <p class="g-pstyle6">Inherits</p>
      <p class="g-pstyle6">$10,000. Buys</p>
      <p class="g-pstyle6">condo with</p>
      <p class="g-pstyle6">high rates.</p>
    </div>
    <div
      id="g-ai0-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:47.6057%;margin-top:-27.8px;left:37.0101%;margin-left:-46.5px;width:93px;"
    >
      <p class="g-pstyle6">Pays off</p>
      <p class="g-pstyle6">student debt.</p>
      <p class="g-pstyle6">Starts investing</p>
      <p class="g-pstyle6">more in 401k.</p>
    </div>
    <div
      id="g-ai0-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:48.0061%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2025</p>
      <p class="g-pstyle5">age 37</p>
    </div>
    <div
      id="g-ai0-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:58.8814%;margin-top:-5.8px;left:73.0746%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle6">Net worth</p>
    </div>
    <div
      id="g-ai0-30"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:70.9865%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2038</p>
      <p class="g-pstyle5">age 50</p>
    </div>
    <div
      id="g-ai0-31"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:70.8925%;margin-top:-5.8px;left:85.2461%;margin-left:-48.5px;width:97px;"
    >
      <p class="g-pstyle6">Inherits $20,000.</p>
    </div>
    <div
      id="g-ai0-32"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.889%;margin-top:-12.4px;left:0.0938%;width:56px;"
    >
      <p class="g-pstyle4">2053</p>
      <p class="g-pstyle5">age 65</p>
    </div>
    <div
      id="g-ai0-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2821%;margin-top:-6.1px;left:20.4538%;margin-left:-35.5px;width:71px;"
    >
      <p class="g-pstyle7">$2 million</p>
    </div>
    <div
      id="g-ai0-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2821%;margin-top:-6.1px;left:38.666%;margin-left:-35.5px;width:71px;"
    >
      <p class="g-pstyle7">$6 million</p>
    </div>
    <div
      id="g-ai0-35"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2821%;margin-top:-6.1px;left:59.6003%;margin-left:-35.5px;width:71px;"
    >
      <p class="g-pstyle7">$6 million</p>
    </div>
    <div
      id="g-ai0-36"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2821%;margin-top:-6.1px;left:85.5921%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle7">$10 million</p>
    </div>
  </div>

  <!-- Artboard: 300px -->
  <div
    id="g-300px"
    class="g-artboard"
    style="max-width: 300px;max-height: 1520px"
    data-aspect-ratio="0.197"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 506.6795% 0;"></div>
    <img
      id="g-300px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_flowchart/300px.png?v=13"
    />
    <div
      id="g-ai1-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:0.4545%;margin-top:-7.9px;left:44.4001%;width:93px;"
    >
      <p class="g-pstyle0">START HERE</p>
    </div>
    <div
      id="g-ai1-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.7658%;margin-top:-5.8px;left:39.1201%;width:125px;"
    >
      <p class="g-pstyle1">Graduates high school.</p>
    </div>
    <div
      id="g-ai1-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:3.9543%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2006</p>
      <p class="g-pstyle3">age 18</p>
    </div>
    <div
      id="g-ai1-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:5.2854%;margin-top:-11.3px;left:85.3314%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle4">Recieves</p>
      <p class="g-pstyle4">pre-college gift.</p>
    </div>
    <div
      id="g-ai1-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1275%;margin-top:-11.3px;left:21.9707%;margin-left:-34.5px;width:69px;"
    >
      <p class="g-pstyle4">Works an</p>
      <p class="g-pstyle4">hourly job.</p>
    </div>
    <div
      id="g-ai1-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.2919%;margin-top:-5.8px;left:56.36%;margin-left:-47px;width:94px;"
    >
      <p class="g-pstyle4">Goes to college.</p>
    </div>
    <div
      id="g-ai1-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:13.9694%;margin-top:-11.3px;left:56.3633%;margin-left:-45px;width:90px;"
    >
      <p class="g-pstyle4">Graduates with</p>
      <p class="g-pstyle4">bachelors.</p>
    </div>
    <div
      id="g-ai1-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.3312%;margin-top:-16.8px;left:85.2523%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle4">Goes straight</p>
      <p class="g-pstyle4">to graduate</p>
      <p class="g-pstyle4">school.</p>
    </div>
    <div
      id="g-ai1-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.3356%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2010</p>
      <p class="g-pstyle3">age 22</p>
    </div>
    <div
      id="g-ai1-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:17.4561%;margin-top:-22.3px;left:37.4193%;margin-left:-38.5px;width:77px;"
    >
      <p class="g-pstyle4">Has debt.</p>
      <p class="g-pstyle4">Works a</p>
      <p class="g-pstyle4">full-time job</p>
      <p class="g-pstyle4">with 401k.</p>
    </div>
    <div
      id="g-ai1-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:16.9298%;margin-top:-11.3px;left:59.3561%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle4">Freelancer.</p>
      <p class="g-pstyle4">Lives at home.</p>
    </div>
    <div
      id="g-ai1-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.2324%;margin-top:-22.3px;left:86.4339%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle4">Graduates with</p>
      <p class="g-pstyle4">masters. Works</p>
      <p class="g-pstyle4">full-time</p>
      <p class="g-pstyle4">with 401k.</p>
    </div>
    <div
      id="g-ai1-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.5614%;margin-top:-11.3px;left:59.3818%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle4">Moves out to</p>
      <p class="g-pstyle4">own apartment.</p>
    </div>
    <div
      id="g-ai1-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.2565%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2013</p>
      <p class="g-pstyle3">age 25</p>
    </div>
    <div
      id="g-ai1-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:23.5744%;margin-top:-22.3px;left:58.3031%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle4">Gets job with</p>
      <p class="g-pstyle4">401k. Doesn&rsquo;t</p>
      <p class="g-pstyle4">max out. Has</p>
      <p class="g-pstyle4">to help family.</p>
    </div>
    <div
      id="g-ai1-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.5612%;margin-top:-11.3px;left:85.391%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle4">Buys home</p>
      <p class="g-pstyle4">with low rates.</p>
    </div>
    <div
      id="g-ai1-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:25.0064%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2015</p>
      <p class="g-pstyle3">age 27</p>
    </div>
    <div
      id="g-ai1-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:32.9163%;margin-top:-22.3px;left:85.3975%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle4">Loses job. Drains</p>
      <p class="g-pstyle4">investment</p>
      <p class="g-pstyle4">portfolio and</p>
      <p class="g-pstyle4">takes from 401k.</p>
    </div>
    <div
      id="g-ai1-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.3768%;margin-top:-22.3px;left:59.3718%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle4">Goes</p>
      <p class="g-pstyle4">part-time to</p>
      <p class="g-pstyle4">help with</p>
      <p class="g-pstyle4">family care.</p>
    </div>
    <div
      id="g-ai1-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.8878%;margin-top:-12.1px;left:0.3897%;width:54px;"
    >
      <p class="g-pstyle2">2020</p>
      <p class="g-pstyle3">age 32</p>
    </div>
    <div
      id="g-ai1-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.7649%;margin-top:-16.8px;left:22.0055%;margin-left:-37px;width:74px;"
    >
      <p class="g-pstyle4">Buys home</p>
      <p class="g-pstyle4">with low</p>
      <p class="g-pstyle4">rates.</p>
    </div>
    <div
      id="g-ai1-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.2386%;margin-top:-5.8px;left:85.318%;margin-left:-47px;width:94px;"
    >
      <p class="g-pstyle4">Returns to work.</p>
    </div>
    <div
      id="g-ai1-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:37.3899%;margin-top:-11.3px;left:59.485%;margin-left:-42.5px;width:85px;"
    >
      <p class="g-pstyle4">Returns to</p>
      <p class="g-pstyle4">work full-time.</p>
    </div>
    <div
      id="g-ai1-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:40.6793%;margin-top:-22.3px;left:59.3535%;margin-left:-43.5px;width:87px;"
    >
      <p class="g-pstyle4">Inherits</p>
      <p class="g-pstyle4">$10,000. Buys</p>
      <p class="g-pstyle4">condo with</p>
      <p class="g-pstyle4">high rates.</p>
    </div>
    <div
      id="g-ai1-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:43.87%;margin-top:-27.8px;left:38.8812%;margin-left:-46.5px;width:93px;"
    >
      <p class="g-pstyle4">Pays off</p>
      <p class="g-pstyle4">student debt.</p>
      <p class="g-pstyle4">Starts investing</p>
      <p class="g-pstyle4">more in 401k.</p>
    </div>
    <div
      id="g-ai1-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:44.2822%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2025</p>
      <p class="g-pstyle3">age 37</p>
    </div>
    <div
      id="g-ai1-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:55.9749%;margin-top:-5.8px;left:73.2149%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle4">Net worth</p>
    </div>
    <div
      id="g-ai1-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:69.0184%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2038</p>
      <p class="g-pstyle3">age 50</p>
    </div>
    <div
      id="g-ai1-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.8693%;margin-top:-5.8px;left:85.3864%;margin-left:-48.5px;width:97px;"
    >
      <p class="g-pstyle4">Inherits $20,000.</p>
    </div>
    <div
      id="g-ai1-30"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.8993%;margin-top:-12.1px;left:0.2341%;width:54px;"
    >
      <p class="g-pstyle2">2053</p>
      <p class="g-pstyle3">age 65</p>
    </div>
    <div
      id="g-ai1-31"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.3466%;margin-top:-6.1px;left:20.2604%;margin-left:-35.5px;width:71px;"
    >
      <p class="g-pstyle5">$2 million</p>
    </div>
    <div
      id="g-ai1-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.3466%;margin-top:-6.1px;left:38.806%;margin-left:-35.5px;width:71px;"
    >
      <p class="g-pstyle5">$6 million</p>
    </div>
    <div
      id="g-ai1-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.3466%;margin-top:-6.1px;left:59.7402%;margin-left:-35.5px;width:71px;"
    >
      <p class="g-pstyle5">$6 million</p>
    </div>
    <div
      id="g-ai1-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.3466%;margin-top:-6.1px;left:85.7324%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle5">$10 million</p>
    </div>
  </div>

  <!-- Artboard: 355px -->
  <div
    id="g-355px"
    class="g-artboard"
    style="width:355px; height:1520.0835556512px;"
    data-aspect-ratio="0.234"
    data-min-width="355"
    data-max-width="619"
  >
    <div style=""></div>
    <img
      id="g-355px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_flowchart/355px.png?v=13"
    />
    <div
      id="g-ai2-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:0.4545%;margin-top:-7.9px;left:41.5064%;width:93px;"
    >
      <p class="g-pstyle0">START HERE</p>
    </div>
    <div
      id="g-ai2-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.7021%;margin-top:-6.9px;left:35.5931%;width:135px;"
    >
      <p class="g-pstyle1">Graduates high school.</p>
    </div>
    <div
      id="g-ai2-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:3.906%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2006</p>
      <p class="g-pstyle3">age 18</p>
    </div>
    <div
      id="g-ai2-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:5.3598%;margin-top:-13.5px;left:85.1378%;margin-left:-49.5px;width:99px;"
    >
      <p class="g-pstyle4">Recieves</p>
      <p class="g-pstyle4">pre-college gift.</p>
    </div>
    <div
      id="g-ai2-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.2018%;margin-top:-13.5px;left:22.8568%;margin-left:-37px;width:74px;"
    >
      <p class="g-pstyle4">Works an</p>
      <p class="g-pstyle4">hourly job.</p>
    </div>
    <div
      id="g-ai2-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.2939%;margin-top:-6.9px;left:56.3012%;margin-left:-50.5px;width:101px;"
    >
      <p class="g-pstyle4">Goes to college.</p>
    </div>
    <div
      id="g-ai2-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.0436%;margin-top:-13.5px;left:55.9246%;margin-left:-48px;width:96px;"
    >
      <p class="g-pstyle4">Graduates with</p>
      <p class="g-pstyle4">bachelors.</p>
    </div>
    <div
      id="g-ai2-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.4778%;margin-top:-20.1px;left:85.052%;margin-left:-44.5px;width:89px;"
    >
      <p class="g-pstyle4">Goes straight</p>
      <p class="g-pstyle4">to graduate</p>
      <p class="g-pstyle4">school.</p>
    </div>
    <div
      id="g-ai2-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.3527%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2010</p>
      <p class="g-pstyle3">age 22</p>
    </div>
    <div
      id="g-ai2-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:17.675%;margin-top:-26.7px;left:38.8413%;margin-left:-41px;width:82px;"
    >
      <p class="g-pstyle4">Has debt.</p>
      <p class="g-pstyle4">Works a</p>
      <p class="g-pstyle4">full-time job</p>
      <p class="g-pstyle4">with 401k.</p>
    </div>
    <div
      id="g-ai2-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:17.0039%;margin-top:-13.5px;left:59.1882%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle4">Freelancer.</p>
      <p class="g-pstyle4">Lives at home.</p>
    </div>
    <div
      id="g-ai2-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.4512%;margin-top:-26.7px;left:86.2385%;margin-left:-49.5px;width:99px;"
    >
      <p class="g-pstyle4">Graduates with</p>
      <p class="g-pstyle4">masters. Works</p>
      <p class="g-pstyle4">full-time</p>
      <p class="g-pstyle4">with 401k.</p>
    </div>
    <div
      id="g-ai2-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.5696%;margin-top:-13.5px;left:59.2721%;margin-left:-49.5px;width:99px;"
    >
      <p class="g-pstyle4">Moves out to</p>
      <p class="g-pstyle4">own apartment.</p>
    </div>
    <div
      id="g-ai2-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.2077%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2013</p>
      <p class="g-pstyle3">age 25</p>
    </div>
    <div
      id="g-ai2-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:23.793%;margin-top:-26.7px;left:59.131%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle4">Gets job with</p>
      <p class="g-pstyle4">401k. Doesn&rsquo;t</p>
      <p class="g-pstyle4">max out. Has</p>
      <p class="g-pstyle4">to help family.</p>
    </div>
    <div
      id="g-ai2-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.6351%;margin-top:-13.5px;left:85.1411%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle4">Buys home</p>
      <p class="g-pstyle4">with low rates.</p>
    </div>
    <div
      id="g-ai2-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.9574%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2015</p>
      <p class="g-pstyle3">age 27</p>
    </div>
    <div
      id="g-ai2-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.0469%;margin-top:-24.3px;left:85.2%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle5">Loses job. Drains</p>
      <p class="g-pstyle5">investment</p>
      <p class="g-pstyle5">portfolio and</p>
      <p class="g-pstyle5">takes from 401k.</p>
    </div>
    <div
      id="g-ai2-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.4416%;margin-top:-24.3px;left:59.2677%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle5">Goes</p>
      <p class="g-pstyle5">part-time to</p>
      <p class="g-pstyle5">help with</p>
      <p class="g-pstyle5">family care.</p>
    </div>
    <div
      id="g-ai2-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.6938%;margin-top:-12.4px;left:0.4528%;width:56px;"
    >
      <p class="g-pstyle2">2020</p>
      <p class="g-pstyle3">age 32</p>
    </div>
    <div
      id="g-ai2-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.7967%;margin-top:-18.3px;left:22.1619%;margin-left:-37px;width:74px;"
    >
      <p class="g-pstyle5">Buys home</p>
      <p class="g-pstyle5">with low</p>
      <p class="g-pstyle5">rates.</p>
    </div>
    <div
      id="g-ai2-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.2704%;margin-top:-6.3px;left:85.1323%;margin-left:-47px;width:94px;"
    >
      <p class="g-pstyle5">Returns to work.</p>
    </div>
    <div
      id="g-ai2-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:37.4545%;margin-top:-12.3px;left:59.3635%;margin-left:-42.5px;width:85px;"
    >
      <p class="g-pstyle5">Returns to</p>
      <p class="g-pstyle5">work full-time.</p>
    </div>
    <div
      id="g-ai2-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:40.8096%;margin-top:-24.3px;left:59.2523%;margin-left:-43.5px;width:87px;"
    >
      <p class="g-pstyle5">Inherits</p>
      <p class="g-pstyle5">$10,000. Buys</p>
      <p class="g-pstyle5">condo with</p>
      <p class="g-pstyle5">high rates.</p>
    </div>
    <div
      id="g-ai2-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:44.0331%;margin-top:-30.3px;left:38.9071%;margin-left:-46.5px;width:93px;"
    >
      <p class="g-pstyle5">Pays off</p>
      <p class="g-pstyle5">student debt.</p>
      <p class="g-pstyle5">Starts investing</p>
      <p class="g-pstyle5">more in 401k.</p>
    </div>
    <div
      id="g-ai2-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:44.2985%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2025</p>
      <p class="g-pstyle3">age 37</p>
    </div>
    <div
      id="g-ai2-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:56.0062%;margin-top:-6.3px;left:73.0617%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle5">Net worth</p>
    </div>
    <div
      id="g-ai2-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.9682%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2038</p>
      <p class="g-pstyle3">age 50</p>
    </div>
    <div
      id="g-ai2-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.9002%;margin-top:-6.3px;left:85.1901%;margin-left:-48.5px;width:97px;"
    >
      <p class="g-pstyle5">Inherits $20,000.</p>
    </div>
    <div
      id="g-ai2-30"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.8482%;margin-top:-12.4px;left:0.2979%;width:56px;"
    >
      <p class="g-pstyle2">2053</p>
      <p class="g-pstyle3">age 65</p>
    </div>
    <div
      id="g-ai2-31"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.359%;margin-top:-6.3px;left:20.6476%;margin-left:-34.5px;width:69px;"
    >
      <p class="g-pstyle6">$2 million</p>
    </div>
    <div
      id="g-ai2-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.359%;margin-top:-6.3px;left:38.8928%;margin-left:-34.5px;width:69px;"
    >
      <p class="g-pstyle6">$6 million</p>
    </div>
    <div
      id="g-ai2-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.359%;margin-top:-6.3px;left:59.6773%;margin-left:-34.5px;width:69px;"
    >
      <p class="g-pstyle6">$6 million</p>
    </div>
    <div
      id="g-ai2-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.359%;margin-top:-6.3px;left:85.4842%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle6">$10 million</p>
    </div>
  </div>

  <!-- Artboard: 620px -->
  <div
    id="g-620px"
    class="g-artboard"
    style="width:620px; height:1720.58989375px;"
    data-aspect-ratio="0.36"
    data-min-width="620"
  >
    <div style=""></div>
    <img
      id="g-620px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_flowchart/620px.png?v=13"
    />
    <div
      id="g-ai3-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:0.4015%;margin-top:-7.9px;left:49.5105%;width:93px;"
    >
      <p class="g-pstyle0">START HERE</p>
    </div>
    <div
      id="g-ai3-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.5058%;margin-top:-7.9px;left:45.2932%;width:146px;"
    >
      <p class="g-pstyle1">Graduates high school.</p>
    </div>
    <div
      id="g-ai3-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:5.3049%;margin-top:-15.3px;left:85.0986%;margin-left:-53px;width:106px;"
    >
      <p class="g-pstyle2">Recieves</p>
      <p class="g-pstyle2">pre-college gift.</p>
    </div>
    <div
      id="g-ai3-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1183%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2006</p>
      <p class="g-pstyle4">age 18</p>
    </div>
    <div
      id="g-ai3-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1066%;margin-top:-15.3px;left:22.1344%;margin-left:-39.5px;width:79px;"
    >
      <p class="g-pstyle2">Works an</p>
      <p class="g-pstyle2">hourly job.</p>
    </div>
    <div
      id="g-ai3-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.0853%;margin-top:-7.9px;left:55.2713%;margin-left:-54px;width:108px;"
    >
      <p class="g-pstyle2">Goes to college.</p>
    </div>
    <div
      id="g-ai3-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:12.8023%;margin-top:-15.3px;left:55.2571%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle2">Graduates with</p>
      <p class="g-pstyle2">bachelors.</p>
    </div>
    <div
      id="g-ai3-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.2185%;margin-top:-22.6px;left:85.1278%;margin-left:-48px;width:96px;"
    >
      <p class="g-pstyle2">Goes straight</p>
      <p class="g-pstyle2">to graduate</p>
      <p class="g-pstyle2">school.</p>
    </div>
    <div
      id="g-ai3-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.1388%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2010</p>
      <p class="g-pstyle4">age 22</p>
    </div>
    <div
      id="g-ai3-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:16.8339%;margin-top:-22.6px;left:37.3619%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">Has debt. Works</p>
      <p class="g-pstyle2">a full-time job</p>
      <p class="g-pstyle2">with a 401k.</p>
    </div>
    <div
      id="g-ai3-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:16.4057%;margin-top:-15.3px;left:59.2734%;margin-left:-57px;width:114px;"
    >
      <p class="g-pstyle2">Works freelance.</p>
      <p class="g-pstyle2">Lives at home.</p>
    </div>
    <div
      id="g-ai3-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:18.7034%;margin-top:-21.8px;left:85.0604%;margin-left:-73px;width:146px;"
    >
      <p class="g-pstyle5">Graduates with</p>
      <p class="g-pstyle5">masters. Starts working</p>
      <p class="g-pstyle5">full-time with 401k.</p>
    </div>
    <div
      id="g-ai3-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:20.5632%;margin-top:-21.8px;left:59.247%;margin-left:-40px;width:80px;"
    >
      <p class="g-pstyle5">Moves out</p>
      <p class="g-pstyle5">to own</p>
      <p class="g-pstyle5">apartment.</p>
    </div>
    <div
      id="g-ai3-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.067%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2013</p>
      <p class="g-pstyle4">age 25</p>
    </div>
    <div
      id="g-ai3-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.341%;margin-top:-21.8px;left:59.2709%;margin-left:-60.5px;width:121px;"
    >
      <p class="g-pstyle5">Gets job with</p>
      <p class="g-pstyle5">401k. Doesn&rsquo;t max</p>
      <p class="g-pstyle5">out. Helps family.</p>
    </div>
    <div
      id="g-ai3-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.3875%;margin-top:-14.6px;left:85.0958%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle5">Buys home</p>
      <p class="g-pstyle5">with low rates.</p>
    </div>
    <div
      id="g-ai3-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.8447%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2015</p>
      <p class="g-pstyle4">age 27</p>
    </div>
    <div
      id="g-ai3-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.9423%;margin-top:-29px;left:85.1764%;margin-left:-59.5px;width:119px;"
    >
      <p class="g-pstyle5">Loses job.</p>
      <p class="g-pstyle5">Drains investment</p>
      <p class="g-pstyle5">portfolio and</p>
      <p class="g-pstyle5">takes from 401k.</p>
    </div>
    <div
      id="g-ai3-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.9307%;margin-top:-21.8px;left:59.2273%;margin-left:-50px;width:100px;"
    >
      <p class="g-pstyle5">Goes part-time</p>
      <p class="g-pstyle5">to help with</p>
      <p class="g-pstyle5">family care.</p>
    </div>
    <div
      id="g-ai3-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.6088%;margin-top:-16.5px;left:0.325%;width:65px;"
    >
      <p class="g-pstyle3">2020</p>
      <p class="g-pstyle4">age 32</p>
    </div>
    <div
      id="g-ai3-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.4182%;margin-top:-14.6px;left:22.0363%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle5">Buys home</p>
      <p class="g-pstyle5">with low rates.</p>
    </div>
    <div
      id="g-ai3-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:37.3481%;margin-top:-14.6px;left:85.1731%;margin-left:-32.5px;width:65px;"
    >
      <p class="g-pstyle5">Returns</p>
      <p class="g-pstyle5">to work.</p>
    </div>
    <div
      id="g-ai3-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:37.9874%;margin-top:-14.6px;left:59.2467%;margin-left:-48.5px;width:97px;"
    >
      <p class="g-pstyle5">Returns to</p>
      <p class="g-pstyle5">work full-time.</p>
    </div>
    <div
      id="g-ai3-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.4281%;margin-top:-21.8px;left:59.2202%;margin-left:-56px;width:112px;"
    >
      <p class="g-pstyle5">Inherits $10,000.</p>
      <p class="g-pstyle5">Buys condo with</p>
      <p class="g-pstyle5">high rates.</p>
    </div>
    <div
      id="g-ai3-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:43.5902%;margin-top:-29px;left:37.3244%;margin-left:-67px;width:134px;"
    >
      <p class="g-pstyle5">Pays off student</p>
      <p class="g-pstyle5">debt. Starts investing</p>
      <p class="g-pstyle5">more in 401k.</p>
    </div>
    <div
      id="g-ai3-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:44.1404%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2025</p>
      <p class="g-pstyle4">age 37</p>
    </div>
    <div
      id="g-ai3-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:49.716%;margin-top:-7.4px;left:77.2263%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle5">Net worth</p>
    </div>
    <div
      id="g-ai3-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.8994%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2038</p>
      <p class="g-pstyle4">age 50</p>
    </div>
    <div
      id="g-ai3-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.7211%;margin-top:-7.4px;left:85.1602%;margin-left:-56px;width:112px;"
    >
      <p class="g-pstyle5">Inherits $20,000.</p>
    </div>
    <div
      id="g-ai3-30"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.843%;margin-top:-16.5px;left:0.1697%;width:65px;"
    >
      <p class="g-pstyle3">2053</p>
      <p class="g-pstyle4">age 65</p>
    </div>
    <div
      id="g-ai3-31"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:22.116%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle6">$2 million</p>
    </div>
    <div
      id="g-ai3-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:37.394%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle6">$6 million</p>
    </div>
    <div
      id="g-ai3-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:59.0992%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle6">$6 million</p>
    </div>
    <div
      id="g-ai3-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:85.1761%;margin-left:-43px;width:86px;"
    >
      <p class="g-pstyle6">$10 million</p>
    </div>
  </div>
</div>
<!-- End ai2html - 2024-08-07 17:52 -->

<style>
  #g-millennials_flowchart-box,
  #g-millennials_flowchart-box .g-artboard {
    margin: 0 auto;
  }
  #g-millennials_flowchart-box p {
    margin: 0;
  }
  #g-millennials_flowchart-box .g-aiAbs {
    position: absolute;
  }
  #g-millennials_flowchart-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
  }
  /* #g-millennials_flowchart-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	} */
  #g-millennials_flowchart-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-app_fallback {
    position: relative;
    overflow: hidden;
  }
  #g-app_fallback p {
    font-weight: 500;
    line-height: 11px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 10px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-app_fallback .g-pstyle0 {
    line-height: 20px;
    font-size: 18px;
  }
  #g-app_fallback .g-pstyle1 {
    line-height: 20px;
    font-size: 15px;
  }
  #g-app_fallback .g-pstyle2 {
    font-weight: 700;
    line-height: 15px;
    height: 15px;
    font-size: 12px;
  }
  #g-app_fallback .g-pstyle3 {
    line-height: 13px;
    height: 13px;
    font-size: 11px;
  }
  #g-app_fallback .g-pstyle4 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 11px;
  }
  #g-app_fallback .g-pstyle5 {
    line-height: 12px;
    height: 12px;
    font-size: 11px;
  }
  #g-app_fallback .g-pstyle6 {
    height: 11px;
    text-align: center;
  }
  #g-app_fallback .g-pstyle7 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 11px;
    text-align: center;
  }
  #g-300px {
    position: relative;
    overflow: hidden;
  }
  #g-300px p {
    font-weight: 500;
    line-height: 11px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 10px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-300px .g-pstyle0 {
    font-weight: 700;
    line-height: 15px;
    height: 15px;
    font-size: 12px;
  }
  #g-300px .g-pstyle1 {
    height: 11px;
  }
  #g-300px .g-pstyle2 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 11px;
  }
  #g-300px .g-pstyle3 {
    line-height: 12px;
    height: 12px;
    font-size: 11px;
  }
  #g-300px .g-pstyle4 {
    height: 11px;
    text-align: center;
  }
  #g-300px .g-pstyle5 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 11px;
    text-align: center;
  }
  #g-355px {
    position: relative;
    overflow: hidden;
  }
  #g-355px p {
    font-weight: 500;
    line-height: 13px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 11px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-355px .g-pstyle0 {
    font-weight: 700;
    line-height: 15px;
    height: 15px;
    font-size: 12px;
  }
  #g-355px .g-pstyle1 {
    height: 13px;
  }
  #g-355px .g-pstyle2 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
  }
  #g-355px .g-pstyle3 {
    line-height: 12px;
    height: 12px;
  }
  #g-355px .g-pstyle4 {
    height: 13px;
    text-align: center;
  }
  #g-355px .g-pstyle5 {
    line-height: 12px;
    height: 12px;
    font-size: 10px;
    text-align: center;
  }
  #g-355px .g-pstyle6 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 10px;
    text-align: center;
  }
  #g-620px {
    position: relative;
    overflow: hidden;
  }
  #g-620px p {
    font-weight: 500;
    line-height: 14px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-620px .g-pstyle0 {
    font-weight: 700;
    line-height: 15px;
    height: 15px;
  }
  #g-620px .g-pstyle1 {
    line-height: 15px;
    height: 15px;
  }
  #g-620px .g-pstyle2 {
    line-height: 15px;
    height: 15px;
    text-align: center;
  }
  #g-620px .g-pstyle3 {
    font-weight: 700;
    line-height: 16px;
    height: 16px;
    font-size: 14px;
  }
  #g-620px .g-pstyle4 {
    line-height: 16px;
    height: 16px;
    font-size: 14px;
  }
  #g-620px .g-pstyle5 {
    height: 14px;
    text-align: center;
  }
  #g-620px .g-pstyle6 {
    font-weight: 700;
    height: 14px;
    text-align: center;
  }

  /* Custom CSS */
  .g-shadow-text {
    padding: 0.5px;
    background-color: white;
  }
</style>
