<!-- Generated by ai2html on 2024-08-22 14:49 -->
<!-- ai file: millennials_flowchart_newdata.ai -->

<script>
  import { onMount } from "svelte";
  onMount(() => {
    (function (containerId, opts) {
      if (!("querySelector" in document)) return;
      var container = document.getElementById(containerId);
      var nameSpace = opts.namespace || "";
      var onResize = throttle(update, 200);
      var waiting = !!window.IntersectionObserver;
      var observer;
      update();

      document.addEventListener("DOMContentLoaded", update);
      window.addEventListener("resize", onResize);

      function update() {
        var artboards = selectChildren(
            "." + nameSpace + "artboard[data-min-width]",
            container
          ),
          width = Math.round(container.getBoundingClientRect().width);

        // Set artboard visibility based on container width
        artboards.forEach(function (el) {
          var minwidth = el.getAttribute("data-min-width"),
            maxwidth = el.getAttribute("data-max-width");
          if (+minwidth <= width && (+maxwidth >= width || maxwidth === null)) {
            if (!waiting) {
              selectChildren("." + nameSpace + "aiImg", el).forEach(
                updateImgSrc
              );
            }
            el.style.display = "block";
          } else {
            el.style.display = "none";
          }
        });

        // Initialize lazy loading on first call
        if (waiting && !observer) {
          if (elementInView(container)) {
            waiting = false;
            update();
          } else {
            observer = new IntersectionObserver(onIntersectionChange, {});
            observer.observe(container);
          }
        }
      }

      function elementInView(el) {
        var bounds = el.getBoundingClientRect();
        return bounds.top < window.innerHeight && bounds.bottom > 0;
      }

      // Replace blank placeholder image with actual image
      function updateImgSrc(img) {
        var src = img.getAttribute("data-src");
        if (src && img.getAttribute("src") != src) {
          img.setAttribute("src", src);
        }
      }

      function onIntersectionChange(entries) {
        // There may be multiple entries relating to the same container
        // (captured at different times)
        var isIntersecting = entries.reduce(function (memo, entry) {
          return memo || entry.isIntersecting;
        }, false);
        if (isIntersecting) {
          waiting = false;
          // update: don't remove -- we need the observer to trigger an update
          // when a hidden map becomes visible after user interaction
          // (e.g. when an accordion menu or tab opens)
          // observer.disconnect();
          // observer = null;
          update();
        }
      }

      function selectChildren(selector, parent) {
        return parent
          ? Array.prototype.slice.call(parent.querySelectorAll(selector))
          : [];
      }

      // based on underscore.js
      function throttle(func, wait) {
        var timeout = null,
          previous = 0;
        function run() {
          previous = Date.now();
          timeout = null;
          func();
        }
        return function () {
          var remaining = wait - (Date.now() - previous);
          if (remaining <= 0 || remaining > wait) {
            clearTimeout(timeout);
            run();
          } else if (!timeout) {
            timeout = setTimeout(run, remaining);
          }
        };
      }
    })("g-millennials_flowchart_newdata-box", {
      namespace: "g-",
      setup: window.setupInteractive || window.getComponent,
    });
  });
</script>

<div id="g-millennials_flowchart_newdata-box" class="ai2html">
  <!-- Artboard: app_fallback -->
  <div
    id="g-app_fallback"
    class="g-artboard"
    style="max-width: 300px;max-height: 1817px"
    data-aspect-ratio="0.165"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 605.7335% 0;"></div>
    <img
      id="g-app_fallback-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      data-src="images/millennials_flowchart_newdata/app_fallback.png?v=14"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="_headline"
      class="g-shadow-text g-aiAbs"
      style="top:0.3302%;left:0%;width:100%;"
    >
      <p class="g-pstyle0">Headline</p>
    </div>
    <div
      id="_description"
      class="g-shadow-text g-aiAbs"
      style="top:1.4858%;left:0%;width:100%;"
    >
      <p class="g-pstyle1">
        Dek&mdash;Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        tempor
      </p>
    </div>
    <div
      id="g-ai0-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:5.0577%;margin-top:-7.9px;left:40.8945%;width:93px;"
    >
      <p class="g-pstyle2">START HERE</p>
    </div>
    <div
      id="g-ai0-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.1032%;margin-top:-7.9px;left:32.1787%;width:146px;"
    >
      <p class="g-pstyle3">Graduates high school.</p>
    </div>
    <div
      id="g-ai0-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:9.8857%;margin-top:-22.6px;left:72.5072%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle4">Invests</p>
      <p class="g-pstyle4">pre-college</p>
      <p class="g-pstyle4">gift.</p>
    </div>
    <div
      id="g-ai0-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:10.801%;margin-top:-15.3px;left:25.7262%;margin-left:-39.5px;width:79px;"
    >
      <p class="g-pstyle5">Works an</p>
      <p class="g-pstyle5">hourly job.</p>
    </div>
    <div
      id="g-ai0-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:10.801%;margin-top:-15.3px;left:51.2848%;margin-left:-32.5px;width:65px;"
    >
      <p class="g-pstyle5">Goes to</p>
      <p class="g-pstyle5">college.</p>
    </div>
    <div
      id="g-ai0-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:10.8633%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2006</p>
      <p class="g-pstyle7">age 18</p>
    </div>
    <div
      id="g-ai0-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:12.1419%;margin-top:-22.6px;left:91.1263%;margin-left:-36px;width:72px;"
    >
      <p class="g-pstyle5">Becomes</p>
      <p class="g-pstyle5">a trade</p>
      <p class="g-pstyle5">worker.</p>
    </div>
    <div
      id="g-ai0-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:16.2691%;margin-top:-22.6px;left:52.8418%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle5">Graduates</p>
      <p class="g-pstyle5">with</p>
      <p class="g-pstyle5">bachelors.</p>
    </div>
    <div
      id="g-ai0-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:16.2691%;margin-top:-22.6px;left:78.2015%;margin-left:-48px;width:96px;"
    >
      <p class="g-pstyle8">Goes straight</p>
      <p class="g-pstyle8">to graduate</p>
      <p class="g-pstyle8">school.</p>
    </div>
    <div
      id="g-ai0-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.2609%;margin-top:-30px;left:36.1452%;margin-left:-44px;width:88px;"
    >
      <p class="g-pstyle5">Has debt.</p>
      <p class="g-pstyle5">Works a</p>
      <p class="g-pstyle5">full-time job</p>
      <p class="g-pstyle5">with a 401k.</p>
    </div>
    <div
      id="g-ai0-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:18.4574%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2010</p>
      <p class="g-pstyle7">age 22</p>
    </div>
    <div
      id="g-ai0-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:22.1994%;margin-top:-28.4px;left:72.4352%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle9">Graduates with</p>
      <p class="g-pstyle9">masters.</p>
      <p class="g-pstyle9">Works full-time</p>
      <p class="g-pstyle9">with 401k.</p>
    </div>
    <div
      id="g-ai0-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.9372%;margin-top:-22.6px;left:18.1882%;margin-left:-35px;width:70px;"
    >
      <p class="g-pstyle5">No 401k,</p>
      <p class="g-pstyle5">saves</p>
      <p class="g-pstyle5">net cash.</p>
    </div>
    <div
      id="g-ai0-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.0704%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2013</p>
      <p class="g-pstyle7">age 25</p>
    </div>
    <div
      id="g-ai0-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.7437%;margin-top:-22.6px;left:54.9857%;margin-left:-32px;width:64px;"
    >
      <p class="g-pstyle5">Starts</p>
      <p class="g-pstyle5">saving</p>
      <p class="g-pstyle5">in 401k.</p>
    </div>
    <div
      id="g-ai0-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:27.6474%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2015</p>
      <p class="g-pstyle7">age 27</p>
    </div>
    <div
      id="g-ai0-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:28.6929%;margin-top:-28.4px;left:72.5212%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle9">Buys a home</p>
      <p class="g-pstyle9">with low rates</p>
      <p class="g-pstyle9">with pre-college</p>
      <p class="g-pstyle9">investment.</p>
    </div>
    <div
      id="g-ai0-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.8412%;margin-top:-59.5px;left:90.1354%;margin-left:-41px;width:82px;"
    >
      <p class="g-pstyle5">Does not</p>
      <p class="g-pstyle5">invest in</p>
      <p class="g-pstyle5">401k.</p>
      <p>&nbsp;</p>
      <p class="g-pstyle5">Invests in</p>
      <p class="g-pstyle5">bull market</p>
      <p class="g-pstyle5">for about</p>
      <p class="g-pstyle5">10 years.</p>
    </div>
    <div
      id="g-ai0-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.6301%;margin-top:-22.6px;left:55.1263%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle5">Gets laid off.</p>
      <p class="g-pstyle5">Unemployed</p>
      <p class="g-pstyle5">for 2 years.</p>
    </div>
    <div
      id="g-ai0-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.7273%;margin-top:-14.4px;left:0.1068%;width:59px;"
    >
      <p class="g-pstyle6">2020</p>
      <p class="g-pstyle7">age 32</p>
    </div>
    <div
      id="g-ai0-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:38.591%;margin-top:-15.3px;left:17.4154%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle5">Buys home</p>
      <p class="g-pstyle5">with low rates.</p>
    </div>
    <div
      id="g-ai0-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:42.1881%;margin-top:-22.6px;left:55.0846%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle5">Buys home</p>
      <p class="g-pstyle5">with higher</p>
      <p class="g-pstyle5">rates.</p>
    </div>
    <div
      id="g-ai0-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:43.8738%;margin-top:-15.3px;left:35.0697%;margin-left:-46.5px;width:93px;"
    >
      <p class="g-pstyle5">Pays off</p>
      <p class="g-pstyle5">student debt.</p>
    </div>
    <div
      id="g-ai0-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:43.8811%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2025</p>
      <p class="g-pstyle7">age 37</p>
    </div>
    <div
      id="g-ai0-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:50.991%;margin-top:-14.6px;left:82.4649%;margin-left:-26.5px;width:53px;"
    >
      <p class="g-pstyle10">Net</p>
      <p class="g-pstyle10">worth</p>
    </div>
    <div
      id="g-ai0-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:69.2425%;margin-top:-15.3px;left:35.0856%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle5">Inherits</p>
      <p class="g-pstyle5">$10,000</p>
    </div>
    <div
      id="g-ai0-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:69.1948%;margin-top:-14.4px;left:72.3926%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle9">Inherits</p>
      <p class="g-pstyle9">$50,000</p>
    </div>
    <div
      id="g-ai0-30"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:69.3599%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2038</p>
      <p class="g-pstyle7">age 50</p>
    </div>
    <div
      id="g-ai0-31"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:96.7646%;margin-top:-14.4px;left:-0.0475%;width:59px;"
    >
      <p class="g-pstyle6">2053</p>
      <p class="g-pstyle7">age 65</p>
    </div>
    <div
      id="g-ai0-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:98.8118%;margin-top:-14.6px;left:16.9889%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle11">$2.4</p>
      <p class="g-pstyle11">million</p>
    </div>
    <div
      id="g-ai0-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:98.8118%;margin-top:-14.6px;left:35.1068%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle11">$3.6</p>
      <p class="g-pstyle11">million</p>
    </div>
    <div
      id="g-ai0-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:98.8118%;margin-top:-14.6px;left:54.8962%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle11">$4.9</p>
      <p class="g-pstyle11">million</p>
    </div>
    <div
      id="g-ai0-35"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:98.8118%;margin-top:-14.6px;left:72.43%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle11">$5</p>
      <p class="g-pstyle11">million</p>
    </div>
    <div
      id="g-ai0-36"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:98.8118%;margin-top:-14.6px;left:91.5134%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle11">$7</p>
      <p class="g-pstyle11">million</p>
    </div>
  </div>

  <!-- Artboard: 300px -->
  <div
    id="g-300px"
    class="g-artboard"
    style="max-width: 300px;max-height: 1734px"
    data-aspect-ratio="0.173"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 578.0307% 0;"></div>
    <img
      id="g-300px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      data-src="images/millennials_flowchart_newdata/300px.png?v=14"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="g-ai1-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:0.3407%;margin-top:-7.9px;left:40.8327%;width:93px;"
    >
      <p class="g-pstyle0">START HERE</p>
    </div>
    <div
      id="g-ai1-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:2.0131%;margin-top:-7.9px;left:32.1165%;width:146px;"
    >
      <p class="g-pstyle1">Graduates high school.</p>
    </div>
    <div
      id="g-ai1-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:5.9767%;margin-top:-22.6px;left:72.4453%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle2">Invests</p>
      <p class="g-pstyle2">pre-college</p>
      <p class="g-pstyle2">gift.</p>
    </div>
    <div
      id="g-ai1-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.9359%;margin-top:-15.3px;left:25.6644%;margin-left:-39.5px;width:79px;"
    >
      <p class="g-pstyle3">Works an</p>
      <p class="g-pstyle3">hourly job.</p>
    </div>
    <div
      id="g-ai1-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.9359%;margin-top:-15.3px;left:51.223%;margin-left:-32.5px;width:65px;"
    >
      <p class="g-pstyle3">Goes to</p>
      <p class="g-pstyle3">college.</p>
    </div>
    <div
      id="g-ai1-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.0013%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2006</p>
      <p class="g-pstyle5">age 18</p>
    </div>
    <div
      id="g-ai1-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:8.3411%;margin-top:-22.6px;left:91.0645%;margin-left:-36px;width:72px;"
    >
      <p class="g-pstyle3">Becomes</p>
      <p class="g-pstyle3">a trade</p>
      <p class="g-pstyle3">worker.</p>
    </div>
    <div
      id="g-ai1-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:12.6661%;margin-top:-22.6px;left:52.78%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle3">Graduates</p>
      <p class="g-pstyle3">with</p>
      <p class="g-pstyle3">bachelors.</p>
    </div>
    <div
      id="g-ai1-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:12.6661%;margin-top:-22.6px;left:78.1397%;margin-left:-48px;width:96px;"
    >
      <p class="g-pstyle6">Goes straight</p>
      <p class="g-pstyle6">to graduate</p>
      <p class="g-pstyle6">school.</p>
    </div>
    <div
      id="g-ai1-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.7437%;margin-top:-30px;left:36.0833%;margin-left:-44px;width:88px;"
    >
      <p class="g-pstyle3">Has debt.</p>
      <p class="g-pstyle3">Works a</p>
      <p class="g-pstyle3">full-time job</p>
      <p class="g-pstyle3">with a 401k.</p>
    </div>
    <div
      id="g-ai1-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.9593%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2010</p>
      <p class="g-pstyle5">age 22</p>
    </div>
    <div
      id="g-ai1-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:18.823%;margin-top:-28.4px;left:72.3734%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle7">Graduates with</p>
      <p class="g-pstyle7">masters.</p>
      <p class="g-pstyle7">Works full-time</p>
      <p class="g-pstyle7">with 401k.</p>
    </div>
    <div
      id="g-ai1-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:18.6058%;margin-top:-22.6px;left:18.1263%;margin-left:-35px;width:70px;"
    >
      <p class="g-pstyle3">No 401k,</p>
      <p class="g-pstyle3">saves</p>
      <p class="g-pstyle3">net cash.</p>
    </div>
    <div
      id="g-ai1-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:20.8413%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2013</p>
      <p class="g-pstyle5">age 25</p>
    </div>
    <div
      id="g-ai1-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.5469%;margin-top:-22.6px;left:54.9238%;margin-left:-32px;width:64px;"
    >
      <p class="g-pstyle3">Starts</p>
      <p class="g-pstyle3">saving</p>
      <p class="g-pstyle3">in 401k.</p>
    </div>
    <div
      id="g-ai1-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.5897%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2015</p>
      <p class="g-pstyle5">age 27</p>
    </div>
    <div
      id="g-ai1-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:25.6277%;margin-top:-28.4px;left:72.4593%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle7">Buys a home</p>
      <p class="g-pstyle7">with low rates</p>
      <p class="g-pstyle7">with pre-college</p>
      <p class="g-pstyle7">investment.</p>
    </div>
    <div
      id="g-ai1-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.2241%;margin-top:-59.5px;left:90.0736%;margin-left:-41px;width:82px;"
    >
      <p class="g-pstyle3">Does not</p>
      <p class="g-pstyle3">invest in</p>
      <p class="g-pstyle3">401k.</p>
      <p>&nbsp;</p>
      <p class="g-pstyle3">Invests in</p>
      <p class="g-pstyle3">bull market</p>
      <p class="g-pstyle3">for about</p>
      <p class="g-pstyle3">10 years.</p>
    </div>
    <div
      id="g-ai1-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.0029%;margin-top:-22.6px;left:55.0645%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle3">Gets laid off.</p>
      <p class="g-pstyle3">Unemployed</p>
      <p class="g-pstyle3">for 2 years.</p>
    </div>
    <div
      id="g-ai1-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.1048%;margin-top:-14.4px;left:0.0449%;width:59px;"
    >
      <p class="g-pstyle4">2020</p>
      <p class="g-pstyle5">age 32</p>
    </div>
    <div
      id="g-ai1-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.0578%;margin-top:-15.3px;left:17.3535%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle3">Buys home</p>
      <p class="g-pstyle3">with low rates.</p>
    </div>
    <div
      id="g-ai1-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:39.8273%;margin-top:-22.6px;left:55.0228%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle3">Buys home</p>
      <p class="g-pstyle3">with higher</p>
      <p class="g-pstyle3">rates.</p>
    </div>
    <div
      id="g-ai1-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.5361%;margin-top:-15.3px;left:35.0078%;margin-left:-46.5px;width:93px;"
    >
      <p class="g-pstyle3">Pays off</p>
      <p class="g-pstyle3">student debt.</p>
    </div>
    <div
      id="g-ai1-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.5438%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2025</p>
      <p class="g-pstyle5">age 37</p>
    </div>
    <div
      id="g-ai1-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:48.9944%;margin-top:-14.6px;left:82.403%;margin-left:-26.5px;width:53px;"
    >
      <p class="g-pstyle8">Net</p>
      <p class="g-pstyle8">worth</p>
    </div>
    <div
      id="g-ai1-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.1783%;margin-top:-15.3px;left:35.0238%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle3">Inherits</p>
      <p class="g-pstyle3">$10,000</p>
    </div>
    <div
      id="g-ai1-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.1283%;margin-top:-14.4px;left:72.3307%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle7">Inherits</p>
      <p class="g-pstyle7">$50,000</p>
    </div>
    <div
      id="g-ai1-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.3013%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2038</p>
      <p class="g-pstyle5">age 50</p>
    </div>
    <div
      id="g-ai1-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.0195%;margin-top:-14.4px;left:-0.1094%;width:59px;"
    >
      <p class="g-pstyle4">2053</p>
      <p class="g-pstyle5">age 65</p>
    </div>
    <div
      id="g-ai1-30"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.1647%;margin-top:-14.6px;left:16.9271%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle9">$2.4</p>
      <p class="g-pstyle9">million</p>
    </div>
    <div
      id="g-ai1-31"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.1647%;margin-top:-14.6px;left:35.0449%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle9">$3.6</p>
      <p class="g-pstyle9">million</p>
    </div>
    <div
      id="g-ai1-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.1647%;margin-top:-14.6px;left:54.8343%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle9">$4.9</p>
      <p class="g-pstyle9">million</p>
    </div>
    <div
      id="g-ai1-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.1647%;margin-top:-14.6px;left:72.3682%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle9">$5</p>
      <p class="g-pstyle9">million</p>
    </div>
    <div
      id="g-ai1-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.1647%;margin-top:-14.6px;left:91.4515%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle9">$7</p>
      <p class="g-pstyle9">million</p>
    </div>
  </div>

  <!-- Artboard: 355px -->
  <div
    id="g-355px"
    class="g-artboard"
    style="width:355px; height:1731.40200475304px;"
    data-aspect-ratio="0.205"
    data-min-width="355"
    data-max-width="619"
  >
    <div style=""></div>
    <img
      id="g-355px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      data-src="images/millennials_flowchart_newdata/355px.png?v=14"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="g-ai2-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:0.2835%;margin-top:-7.9px;left:48.1652%;width:93px;"
    >
      <p class="g-pstyle0">START HERE</p>
    </div>
    <div
      id="g-ai2-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.3809%;margin-top:-7.9px;left:43.9266%;width:146px;"
    >
      <p class="g-pstyle1">Graduates high school.</p>
    </div>
    <div
      id="g-ai2-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.4115%;margin-top:-30px;left:72.3462%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle2">Recieves</p>
      <p class="g-pstyle2">and invests</p>
      <p class="g-pstyle2">pre-college</p>
      <p class="g-pstyle2">gift.</p>
    </div>
    <div
      id="g-ai2-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.8312%;margin-top:-15.3px;left:24.9609%;margin-left:-39.5px;width:79px;"
    >
      <p class="g-pstyle2">Works an</p>
      <p class="g-pstyle2">hourly job.</p>
    </div>
    <div
      id="g-ai2-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.8312%;margin-top:-15.3px;left:52.8667%;margin-left:-32.5px;width:65px;"
    >
      <p class="g-pstyle2">Goes to</p>
      <p class="g-pstyle2">college.</p>
    </div>
    <div
      id="g-ai2-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.9544%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2006</p>
      <p class="g-pstyle4">age 18</p>
    </div>
    <div
      id="g-ai2-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:8.2963%;margin-top:-22.6px;left:91.5402%;margin-left:-36px;width:72px;"
    >
      <p class="g-pstyle2">Becomes</p>
      <p class="g-pstyle2">a trade</p>
      <p class="g-pstyle2">worker.</p>
    </div>
    <div
      id="g-ai2-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.3608%;margin-top:-22.6px;left:52.4279%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle2">Graduates</p>
      <p class="g-pstyle2">with</p>
      <p class="g-pstyle2">bachelors.</p>
    </div>
    <div
      id="g-ai2-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.3608%;margin-top:-22.6px;left:72.9289%;margin-left:-48px;width:96px;"
    >
      <p class="g-pstyle2">Goes straight</p>
      <p class="g-pstyle2">to graduate</p>
      <p class="g-pstyle2">school.</p>
    </div>
    <div
      id="g-ai2-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.7104%;margin-top:-30px;left:17.335%;margin-left:-35px;width:70px;"
    >
      <p class="g-pstyle2">No 401k,</p>
      <p class="g-pstyle2">begins</p>
      <p class="g-pstyle2">saving</p>
      <p class="g-pstyle2">net cash.</p>
    </div>
    <div
      id="g-ai2-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.7104%;margin-top:-30px;left:35.51%;margin-left:-44px;width:88px;"
    >
      <p class="g-pstyle2">Has debt.</p>
      <p class="g-pstyle2">Works a</p>
      <p class="g-pstyle2">full-time job</p>
      <p class="g-pstyle2">with a 401k.</p>
    </div>
    <div
      id="g-ai2-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.9248%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2010</p>
      <p class="g-pstyle4">age 22</p>
    </div>
    <div
      id="g-ai2-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:19.245%;margin-top:-36.2px;left:72.2805%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle5">Graduates with</p>
      <p class="g-pstyle5">masters.</p>
      <p class="g-pstyle5">Starts working</p>
      <p class="g-pstyle5">full-time</p>
      <p class="g-pstyle5">with 401k.</p>
    </div>
    <div
      id="g-ai2-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.1183%;margin-top:-22.6px;left:54.6127%;margin-left:-32px;width:64px;"
    >
      <p class="g-pstyle2">Starts</p>
      <p class="g-pstyle2">saving</p>
      <p class="g-pstyle2">in 401k.</p>
    </div>
    <div
      id="g-ai2-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:20.816%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2013</p>
      <p class="g-pstyle4">age 25</p>
    </div>
    <div
      id="g-ai2-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.5702%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2015</p>
      <p class="g-pstyle4">age 27</p>
    </div>
    <div
      id="g-ai2-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:25.5868%;margin-top:-30px;left:72.3528%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">Buys a home</p>
      <p class="g-pstyle2">with low rates</p>
      <p class="g-pstyle2">with pre-college</p>
      <p class="g-pstyle2">investment.</p>
    </div>
    <div
      id="g-ai2-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.2195%;margin-top:-59.5px;left:91.5551%;margin-left:-41px;width:82px;"
    >
      <p class="g-pstyle2">Does not</p>
      <p class="g-pstyle2">invest in</p>
      <p class="g-pstyle2">401k.</p>
      <p>&nbsp;</p>
      <p class="g-pstyle2">Invests in</p>
      <p class="g-pstyle2">bull market</p>
      <p class="g-pstyle2">for about</p>
      <p class="g-pstyle2">10 years.</p>
    </div>
    <div
      id="g-ai2-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.998%;margin-top:-22.6px;left:54.7315%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle2">Gets laid off.</p>
      <p class="g-pstyle2">Unemployed</p>
      <p class="g-pstyle2">for 2 years.</p>
    </div>
    <div
      id="g-ai2-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.1%;margin-top:-14.4px;left:0.3711%;width:59px;"
    >
      <p class="g-pstyle3">2020</p>
      <p class="g-pstyle4">age 32</p>
    </div>
    <div
      id="g-ai2-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:36.056%;margin-top:-15.3px;left:16.5631%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle2">Buys home</p>
      <p class="g-pstyle2">with low rates.</p>
    </div>
    <div
      id="g-ai2-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:39.8314%;margin-top:-22.6px;left:54.6963%;margin-left:-41.5px;width:83px;"
    >
      <p class="g-pstyle2">Buys home</p>
      <p class="g-pstyle2">with higher</p>
      <p class="g-pstyle2">rates.</p>
    </div>
    <div
      id="g-ai2-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.5429%;margin-top:-15.3px;left:34.4457%;margin-left:-46.5px;width:93px;"
    >
      <p class="g-pstyle2">Pays off</p>
      <p class="g-pstyle2">student debt.</p>
    </div>
    <div
      id="g-ai2-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.5506%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2025</p>
      <p class="g-pstyle4">age 37</p>
    </div>
    <div
      id="g-ai2-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:49.29%;margin-top:-7.4px;left:81.8307%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle5">Net worth</p>
    </div>
    <div
      id="g-ai2-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.2265%;margin-top:-15.3px;left:34.4592%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle2">Inherits</p>
      <p class="g-pstyle2">$10,000</p>
    </div>
    <div
      id="g-ai2-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.2265%;margin-top:-15.3px;left:72.2442%;margin-left:-33px;width:66px;"
    >
      <p class="g-pstyle2">Inherits</p>
      <p class="g-pstyle2">$50,000</p>
    </div>
    <div
      id="g-ai2-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.3497%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2038</p>
      <p class="g-pstyle4">age 50</p>
    </div>
    <div
      id="g-ai2-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.1125%;margin-top:-14.4px;left:0.2149%;width:59px;"
    >
      <p class="g-pstyle3">2053</p>
      <p class="g-pstyle4">age 65</p>
    </div>
    <div
      id="g-ai2-30"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2611%;margin-top:-14.6px;left:16.1138%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle6">$2.4</p>
      <p class="g-pstyle6">million</p>
    </div>
    <div
      id="g-ai2-31"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2611%;margin-top:-14.6px;left:34.4639%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle6">$3.6</p>
      <p class="g-pstyle6">million</p>
    </div>
    <div
      id="g-ai2-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2611%;margin-top:-14.6px;left:54.507%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle6">$4.9</p>
      <p class="g-pstyle6">million</p>
    </div>
    <div
      id="g-ai2-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2611%;margin-top:-14.6px;left:72.2656%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle6">$5</p>
      <p class="g-pstyle6">million</p>
    </div>
    <div
      id="g-ai2-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.2611%;margin-top:-14.6px;left:91.5933%;margin-left:-30.5px;width:61px;"
    >
      <p class="g-pstyle6">$7</p>
      <p class="g-pstyle6">million</p>
    </div>
  </div>

  <!-- Artboard: 620px -->
  <div
    id="g-620px"
    class="g-artboard"
    style="width:620px; height:1720.58989375px;"
    data-aspect-ratio="0.36"
    data-min-width="620"
  >
    <div style=""></div>
    <img
      id="g-620px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      data-src="images/millennials_flowchart_newdata/620px.png?v=14"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="g-ai3-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:0.4015%;margin-top:-7.9px;left:48.1742%;width:93px;"
    >
      <p class="g-pstyle0">START HERE</p>
    </div>
    <div
      id="g-ai3-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.5058%;margin-top:-7.9px;left:43.9568%;width:146px;"
    >
      <p class="g-pstyle1">Graduates high school.</p>
    </div>
    <div
      id="g-ai3-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:6.0023%;margin-top:-15.3px;left:72.1839%;margin-left:-66.5px;width:133px;"
    >
      <p class="g-pstyle2">Recieves and invests</p>
      <p class="g-pstyle2">pre-college gift.</p>
    </div>
    <div
      id="g-ai3-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1183%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2006</p>
      <p class="g-pstyle4">age 18</p>
    </div>
    <div
      id="g-ai3-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1066%;margin-top:-15.3px;left:16.6613%;margin-left:-39.5px;width:79px;"
    >
      <p class="g-pstyle2">Works an</p>
      <p class="g-pstyle2">hourly job.</p>
    </div>
    <div
      id="g-ai3-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.1066%;margin-top:-15.3px;left:91.2782%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle2">Becomes a</p>
      <p class="g-pstyle2">trade worker.</p>
    </div>
    <div
      id="g-ai3-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:7.8989%;margin-top:-7.9px;left:54.6406%;margin-left:-54px;width:108px;"
    >
      <p class="g-pstyle2">Goes to college.</p>
    </div>
    <div
      id="g-ai3-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.451%;margin-top:-22.6px;left:72.7864%;margin-left:-48px;width:96px;"
    >
      <p class="g-pstyle2">Goes straight</p>
      <p class="g-pstyle2">to graduate</p>
      <p class="g-pstyle2">school.</p>
    </div>
    <div
      id="g-ai3-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.4297%;margin-top:-15.3px;left:54.6264%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle2">Graduates with</p>
      <p class="g-pstyle2">bachelors.</p>
    </div>
    <div
      id="g-ai3-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.0109%;margin-top:-15.3px;left:16.6309%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">No 401k, begins</p>
      <p class="g-pstyle2">saving net cash.</p>
    </div>
    <div
      id="g-ai3-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:15.1388%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2010</p>
      <p class="g-pstyle4">age 22</p>
    </div>
    <div
      id="g-ai3-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:16.8339%;margin-top:-22.6px;left:34.6504%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">Has debt. Works</p>
      <p class="g-pstyle2">a full-time job</p>
      <p class="g-pstyle2">with a 401k.</p>
    </div>
    <div
      id="g-ai3-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:18.6452%;margin-top:-21.8px;left:72.1871%;margin-left:-73px;width:146px;"
    >
      <p class="g-pstyle5">Graduates with</p>
      <p class="g-pstyle5">masters. Starts working</p>
      <p class="g-pstyle5">full-time with 401k.</p>
    </div>
    <div
      id="g-ai3-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.067%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2013</p>
      <p class="g-pstyle4">age 25</p>
    </div>
    <div
      id="g-ai3-15"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:21.0553%;margin-top:-15.3px;left:54.6088%;margin-left:-45px;width:90px;"
    >
      <p class="g-pstyle2">Starts saving</p>
      <p class="g-pstyle2">in 401k.</p>
    </div>
    <div
      id="g-ai3-16"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:24.8447%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2015</p>
      <p class="g-pstyle4">age 27</p>
    </div>
    <div
      id="g-ai3-17"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:25.8638%;margin-top:-30px;left:72.2186%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">Buys a home</p>
      <p class="g-pstyle2">with low rates</p>
      <p class="g-pstyle2">with pre-college</p>
      <p class="g-pstyle2">investment.</p>
    </div>
    <div
      id="g-ai3-18"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:33.1868%;margin-top:-30px;left:91.3827%;margin-left:-60.5px;width:121px;"
    >
      <p class="g-pstyle2">Does not invest in</p>
      <p class="g-pstyle2">401k, but invests</p>
      <p class="g-pstyle2">in a bull market for</p>
      <p class="g-pstyle2">about 10 years.</p>
    </div>
    <div
      id="g-ai3-19"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.4441%;margin-top:-22.6px;left:54.6781%;margin-left:-46px;width:92px;"
    >
      <p class="g-pstyle2">Gets laid off.</p>
      <p class="g-pstyle2">Unemployed</p>
      <p class="g-pstyle2">for 2 years.</p>
    </div>
    <div
      id="g-ai3-20"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.6088%;margin-top:-16.5px;left:0.6194%;width:65px;"
    >
      <p class="g-pstyle3">2020</p>
      <p class="g-pstyle4">age 32</p>
    </div>
    <div
      id="g-ai3-21"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:35.8758%;margin-top:-15.3px;left:16.7553%;margin-left:-49px;width:98px;"
    >
      <p class="g-pstyle2">Buys home</p>
      <p class="g-pstyle2">with low rates.</p>
    </div>
    <div
      id="g-ai3-22"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:39.7698%;margin-top:-15.3px;left:54.6688%;margin-left:-54px;width:108px;"
    >
      <p class="g-pstyle2">Buys home with</p>
      <p class="g-pstyle2">higher rates.</p>
    </div>
    <div
      id="g-ai3-23"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.9319%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2025</p>
      <p class="g-pstyle4">age 37</p>
    </div>
    <div
      id="g-ai3-24"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:41.7245%;margin-top:-7.9px;left:34.6025%;margin-left:-69px;width:138px;"
    >
      <p class="g-pstyle2">Pays off student debt.</p>
    </div>
    <div
      id="g-ai3-25"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:49.716%;margin-top:-7.4px;left:83.3429%;margin-left:-37.5px;width:75px;"
    >
      <p class="g-pstyle5">Net worth</p>
    </div>
    <div
      id="g-ai3-26"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.8994%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2038</p>
      <p class="g-pstyle4">age 50</p>
    </div>
    <div
      id="g-ai3-27"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.692%;margin-top:-7.9px;left:34.5881%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">Inherits $10,000</p>
    </div>
    <div
      id="g-ai3-28"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:68.692%;margin-top:-7.9px;left:72.1838%;margin-left:-54.5px;width:109px;"
    >
      <p class="g-pstyle2">Inherits $50,000</p>
    </div>
    <div
      id="g-ai3-29"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:97.843%;margin-top:-16.5px;left:0.4641%;width:65px;"
    >
      <p class="g-pstyle3">2053</p>
      <p class="g-pstyle4">age 65</p>
    </div>
    <div
      id="g-ai3-30"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:16.8506%;margin-left:-44.5px;width:89px;"
    >
      <p class="g-pstyle6">$2.4 million</p>
    </div>
    <div
      id="g-ai3-31"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:34.548%;margin-left:-44.5px;width:89px;"
    >
      <p class="g-pstyle6">$3.6 million</p>
    </div>
    <div
      id="g-ai3-32"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:54.491%;margin-left:-44.5px;width:89px;"
    >
      <p class="g-pstyle6">$4.9 million</p>
    </div>
    <div
      id="g-ai3-33"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:72.1152%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle6">$5 million</p>
    </div>
    <div
      id="g-ai3-34"
      class="g-other_text g-aiAbs g-aiPointText"
      style="top:99.292%;margin-top:-7.4px;left:91.3463%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle6">$7 million</p>
    </div>
  </div>
</div>
<!-- End ai2html - 2024-08-22 14:49 -->

<style>
  #g-millennials_flowchart_newdata-box,
  #g-millennials_flowchart_newdata-box .g-artboard {
    margin: 0 auto;
  }
  #g-millennials_flowchart_newdata-box p {
    margin: 0;
  }
  #g-millennials_flowchart_newdata-box .g-aiAbs {
    position: absolute;
  }
  #g-millennials_flowchart_newdata-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
  }
  /* #g-millennials_flowchart_newdata-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	} */
  #g-millennials_flowchart_newdata-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-app_fallback {
    position: relative;
    overflow: hidden;
  }
  #g-app_fallback p {
    font-weight: 500;
    line-height: 15px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-app_fallback .g-pstyle0 {
    line-height: 20px;
    font-size: 18px;
  }
  #g-app_fallback .g-pstyle1 {
    line-height: 20px;
    font-size: 15px;
  }
  #g-app_fallback .g-pstyle2 {
    font-weight: 700;
    height: 15px;
  }
  #g-app_fallback .g-pstyle3 {
    height: 15px;
  }
  #g-app_fallback .g-pstyle4 {
    height: 15px;
    mix-blend-mode: multiply;
    text-align: center;
    color: rgb(15, 119, 147);
  }
  #g-app_fallback .g-pstyle5 {
    height: 15px;
    text-align: center;
  }
  #g-app_fallback .g-pstyle6 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
  }
  #g-app_fallback .g-pstyle7 {
    line-height: 14px;
    height: 14px;
  }
  #g-app_fallback .g-pstyle8 {
    height: 15px;
    text-align: center;
    color: rgb(15, 119, 147);
  }
  #g-app_fallback .g-pstyle9 {
    line-height: 14px;
    height: 14px;
    text-align: center;
    color: rgb(15, 119, 147);
  }
  #g-app_fallback .g-pstyle10 {
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-app_fallback .g-pstyle11 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-300px {
    position: relative;
    overflow: hidden;
  }
  #g-300px p {
    font-weight: 500;
    line-height: 15px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-300px .g-pstyle0 {
    font-weight: 700;
    height: 15px;
  }
  #g-300px .g-pstyle1 {
    height: 15px;
  }
  #g-300px .g-pstyle2 {
    height: 15px;
    mix-blend-mode: multiply;
    text-align: center;
    color: rgb(15, 119, 147);
  }
  #g-300px .g-pstyle3 {
    height: 15px;
    text-align: center;
  }
  #g-300px .g-pstyle4 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
  }
  #g-300px .g-pstyle5 {
    line-height: 14px;
    height: 14px;
  }
  #g-300px .g-pstyle6 {
    height: 15px;
    text-align: center;
    color: rgb(15, 119, 147);
  }
  #g-300px .g-pstyle7 {
    line-height: 14px;
    height: 14px;
    text-align: center;
    color: rgb(15, 119, 147);
  }
  #g-300px .g-pstyle8 {
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-300px .g-pstyle9 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-355px {
    position: relative;
    overflow: hidden;
  }
  #g-355px p {
    font-weight: 500;
    line-height: 15px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-355px .g-pstyle0 {
    font-weight: 700;
    height: 15px;
  }
  #g-355px .g-pstyle1 {
    height: 15px;
  }
  #g-355px .g-pstyle2 {
    height: 15px;
    text-align: center;
  }
  #g-355px .g-pstyle3 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
  }
  #g-355px .g-pstyle4 {
    line-height: 14px;
    height: 14px;
  }
  #g-355px .g-pstyle5 {
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-355px .g-pstyle6 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-620px {
    position: relative;
    overflow: hidden;
  }
  #g-620px p {
    font-weight: 500;
    line-height: 15px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-620px .g-pstyle0 {
    font-weight: 700;
    height: 15px;
  }
  #g-620px .g-pstyle1 {
    height: 15px;
  }
  #g-620px .g-pstyle2 {
    height: 15px;
    text-align: center;
  }
  #g-620px .g-pstyle3 {
    font-weight: 700;
    line-height: 16px;
    height: 16px;
    font-size: 14px;
  }
  #g-620px .g-pstyle4 {
    line-height: 16px;
    height: 16px;
    font-size: 14px;
  }
  #g-620px .g-pstyle5 {
    line-height: 14px;
    height: 14px;
    text-align: center;
  }
  #g-620px .g-pstyle6 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    text-align: center;
  }

  /* Custom CSS */
  .g-shadow-text {
    padding: 0.5px;
    background-color: white;
  }
</style>
