<!-- Generated by ai2html on 2024-08-08 10:04 -->
<!-- ai file: millennials_bar.ai -->

<script>
  import { onMount } from "svelte";
  onMount(() => {
    (function (containerId, opts) {
      if (!("querySelector" in document)) return;
      var container = document.getElementById(containerId);
      var nameSpace = opts.namespace || "";
      var onResize = throttle(update, 200);
      var waiting = !!window.IntersectionObserver;
      var observer;
      update();

      document.addEventListener("DOMContentLoaded", update);
      window.addEventListener("resize", onResize);

      function update() {
        var artboards = selectChildren(
            "." + nameSpace + "artboard[data-min-width]",
            container
          ),
          width = Math.round(container.getBoundingClientRect().width);

        // Set artboard visibility based on container width
        artboards.forEach(function (el) {
          var minwidth = el.getAttribute("data-min-width"),
            maxwidth = el.getAttribute("data-max-width");
          if (+minwidth <= width && (+maxwidth >= width || maxwidth === null)) {
            if (!waiting) {
              selectChildren("." + nameSpace + "aiImg", el).forEach(
                updateImgSrc
              );
            }
            el.style.display = "block";
          } else {
            el.style.display = "none";
          }
        });

        // Initialize lazy loading on first call
        if (waiting && !observer) {
          if (elementInView(container)) {
            waiting = false;
            update();
          } else {
            observer = new IntersectionObserver(onIntersectionChange, {});
            observer.observe(container);
          }
        }
      }

      function elementInView(el) {
        var bounds = el.getBoundingClientRect();
        return bounds.top < window.innerHeight && bounds.bottom > 0;
      }

      // Replace blank placeholder image with actual image
      function updateImgSrc(img) {
        var src = img.getAttribute("data-src");
        if (src && img.getAttribute("src") != src) {
          img.setAttribute("src", src);
        }
      }

      function onIntersectionChange(entries) {
        // There may be multiple entries relating to the same container
        // (captured at different times)
        var isIntersecting = entries.reduce(function (memo, entry) {
          return memo || entry.isIntersecting;
        }, false);
        if (isIntersecting) {
          waiting = false;
          // update: don't remove -- we need the observer to trigger an update
          // when a hidden map becomes visible after user interaction
          // (e.g. when an accordion menu or tab opens)
          // observer.disconnect();
          // observer = null;
          update();
        }
      }

      function selectChildren(selector, parent) {
        return parent
          ? Array.prototype.slice.call(parent.querySelectorAll(selector))
          : [];
      }

      // based on underscore.js
      function throttle(func, wait) {
        var timeout = null,
          previous = 0;
        function run() {
          previous = Date.now();
          timeout = null;
          func();
        }
        return function () {
          var remaining = wait - (Date.now() - previous);
          if (remaining <= 0 || remaining > wait) {
            clearTimeout(timeout);
            run();
          } else if (!timeout) {
            timeout = setTimeout(run, remaining);
          }
        };
      }
    })("g-millennials_bar-box", {
      namespace: "g-",
      setup: window.setupInteractive || window.getComponent,
    });
  });
</script>

<div id="g-millennials_bar-box" class="ai2html">
  <!-- Artboard: app_fallback -->
  <div
    id="g-app_fallback"
    class="g-artboard"
    style="max-width: 300px;max-height: 534px"
    data-aspect-ratio="0.562"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 178% 0;"></div>
    <img
      id="g-app_fallback-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_bar/app_fallback.png?v=13"
    />
    <div
      id="_headline"
      class="g-GFX g-aiAbs"
      style="top:1.1236%;left:0%;width:100%;"
    >
      <p class="g-pstyle0">Headline</p>
    </div>
    <div
      id="_description"
      class="g-GFX g-aiAbs"
      style="top:5.0562%;left:0%;width:100%;"
    >
      <p>
        Dek&mdash;Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        tempor
      </p>
    </div>
    <div
      id="_title"
      class="g-GFX g-aiAbs"
      style="top:14.4195%;left:0%;width:100%;"
    >
      <p class="g-pstyle1">Chart title</p>
    </div>
    <div
      id="g-ai0-4"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:21.612%;margin-top:-7.4px;left:-0.012%;width:121px;"
    >
      <p class="g-pstyle2">$10 million dollars</p>
    </div>
    <div
      id="g-ai0-5"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:23.6719%;margin-top:-6.4px;right:22.331%;width:56px;"
    >
      <p class="g-pstyle3">Home</p>
    </div>
    <div
      id="g-ai0-6"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:27.9812%;margin-top:-12.4px;right:22.2106%;width:92px;"
    >
      <p class="g-pstyle4">Taxable</p>
      <p class="g-pstyle4">investments</p>
    </div>
    <div
      id="g-ai0-7"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:32.2862%;margin-top:-7.4px;right:22.9329%;width:52px;"
    >
      <p class="g-pstyle5">401k</p>
    </div>
    <div
      id="g-ai0-8"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:33.9716%;margin-top:-7.4px;left:-0.012%;width:29px;"
    >
      <p class="g-pstyle2">8</p>
    </div>
    <div
      id="g-ai0-9"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:46.1439%;margin-top:-7.4px;left:-0.012%;width:29px;"
    >
      <p class="g-pstyle2">6</p>
    </div>
    <div
      id="g-ai0-10"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:58.3161%;margin-top:-7.4px;left:-0.012%;width:29px;"
    >
      <p class="g-pstyle2">4</p>
    </div>
    <div
      id="g-ai0-11"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:70.6757%;margin-top:-7.4px;left:-0.012%;width:29px;"
    >
      <p class="g-pstyle2">2</p>
    </div>
    <div
      id="g-ai0-12"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:82.848%;margin-top:-7.4px;left:-0.012%;width:29px;"
    >
      <p class="g-pstyle2">0</p>
    </div>
    <div
      id="g-ai0-13"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:86.1251%;margin-top:-6.9px;left:5.2542%;width:80px;"
    >
      <p class="g-pstyle6">No college</p>
    </div>
    <div
      id="g-ai0-14"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:87.3424%;margin-top:-13.4px;left:30.6585%;width:75px;"
    >
      <p class="g-pstyle6">Bachelors</p>
      <p class="g-pstyle6">with debt</p>
    </div>
    <div
      id="g-ai0-15"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:86.1251%;margin-top:-6.9px;left:54.8659%;width:75px;"
    >
      <p class="g-pstyle6">Bachelors</p>
    </div>
    <div
      id="g-ai0-16"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:86.1251%;margin-top:-6.9px;left:81.8548%;width:64px;"
    >
      <p class="g-pstyle6">Masters</p>
    </div>
    <div
      id="_note"
      class="g-GFX g-aiAbs"
      style="top:93.4457%;left:0%;width:100%;"
    >
      <p class="g-pstyle7">Note:</p>
    </div>
    <div
      id="_source"
      class="g-GFX g-aiAbs"
      style="top:97.191%;left:0%;width:100%;"
    >
      <p class="g-pstyle7">Source:</p>
    </div>
  </div>

  <!-- Artboard: 300px -->
  <div
    id="g-300px"
    class="g-artboard"
    style="max-width: 300px;max-height: 370px"
    data-aspect-ratio="0.811"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 123.3333% 0;"></div>
    <img
      id="g-300px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_bar/300px.png?v=13"
    />
    <div
      id="g-ai1-1"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:1.4617%;margin-top:-7.4px;left:0.1452%;width:121px;"
    >
      <p class="g-pstyle0">$10 million dollars</p>
    </div>
    <div
      id="g-ai1-2"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:4.4346%;margin-top:-6.4px;right:22.6969%;width:56px;"
    >
      <p class="g-pstyle1">Home</p>
    </div>
    <div
      id="g-ai1-3"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:10.6539%;margin-top:-12.4px;right:22.5768%;width:92px;"
    >
      <p class="g-pstyle2">Taxable</p>
      <p class="g-pstyle2">investments</p>
    </div>
    <div
      id="g-ai1-4"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:16.8671%;margin-top:-7.4px;right:23.2991%;width:52px;"
    >
      <p class="g-pstyle3">401k</p>
    </div>
    <div
      id="g-ai1-5"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:19.2995%;margin-top:-7.4px;left:0.1452%;width:29px;"
    >
      <p class="g-pstyle0">8</p>
    </div>
    <div
      id="g-ai1-6"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:36.8671%;margin-top:-7.4px;left:0.1452%;width:29px;"
    >
      <p class="g-pstyle0">6</p>
    </div>
    <div
      id="g-ai1-7"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:54.4346%;margin-top:-7.4px;left:0.1452%;width:29px;"
    >
      <p class="g-pstyle0">4</p>
    </div>
    <div
      id="g-ai1-8"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:72.2725%;margin-top:-7.4px;left:0.1452%;width:29px;"
    >
      <p class="g-pstyle0">2</p>
    </div>
    <div
      id="g-ai1-9"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:89.8401%;margin-top:-7.4px;left:0.1452%;width:29px;"
    >
      <p class="g-pstyle0">0</p>
    </div>
    <div
      id="g-ai1-10"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:5.071%;width:80px;"
    >
      <p class="g-pstyle4">No college</p>
    </div>
    <div
      id="g-ai1-11"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:96.3265%;margin-top:-13.4px;left:30.4356%;width:75px;"
    >
      <p class="g-pstyle4">Bachelors</p>
      <p class="g-pstyle4">with debt</p>
    </div>
    <div
      id="g-ai1-12"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:54.9378%;width:75px;"
    >
      <p class="g-pstyle4">Bachelors</p>
    </div>
    <div
      id="g-ai1-13"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:81.5514%;width:64px;"
    >
      <p class="g-pstyle4">Masters</p>
    </div>
  </div>

  <!-- Artboard: 355px -->
  <div
    id="g-355px"
    class="g-artboard"
    style="width:355px; height:370px;"
    data-aspect-ratio="0.959"
    data-min-width="355"
    data-max-width="619"
  >
    <div style=""></div>
    <img
      id="g-355px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_bar/355px.png?v=13"
    />
    <div
      id="g-ai2-1"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:1.4617%;margin-top:-7.4px;left:0.2979%;width:121px;"
    >
      <p class="g-pstyle0">$10 million dollars</p>
    </div>
    <div
      id="g-ai2-2"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:4.1644%;margin-top:-6.4px;right:21.7237%;width:56px;"
    >
      <p class="g-pstyle1">Home</p>
    </div>
    <div
      id="g-ai2-3"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:10.3836%;margin-top:-12.4px;right:21.6222%;width:92px;"
    >
      <p class="g-pstyle2">Taxable</p>
      <p class="g-pstyle2">investments</p>
    </div>
    <div
      id="g-ai2-4"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:16.5968%;margin-top:-7.4px;right:22.2326%;width:52px;"
    >
      <p class="g-pstyle3">401k</p>
    </div>
    <div
      id="g-ai2-5"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:19.2995%;margin-top:-7.4px;left:0.2979%;width:29px;"
    >
      <p class="g-pstyle0">8</p>
    </div>
    <div
      id="g-ai2-6"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:36.8671%;margin-top:-7.4px;left:0.2979%;width:29px;"
    >
      <p class="g-pstyle0">6</p>
    </div>
    <div
      id="g-ai2-7"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:54.4346%;margin-top:-7.4px;left:0.2979%;width:29px;"
    >
      <p class="g-pstyle0">4</p>
    </div>
    <div
      id="g-ai2-8"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:72.2725%;margin-top:-7.4px;left:0.2979%;width:29px;"
    >
      <p class="g-pstyle0">2</p>
    </div>
    <div
      id="g-ai2-9"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:89.8401%;margin-top:-7.4px;left:0.2979%;width:29px;"
    >
      <p class="g-pstyle0">0</p>
    </div>
    <div
      id="g-ai2-10"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:9.3624%;width:80px;"
    >
      <p class="g-pstyle4">No college</p>
    </div>
    <div
      id="g-ai2-11"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:96.3265%;margin-top:-13.4px;left:33.9217%;width:75px;"
    >
      <p class="g-pstyle4">Bachelors</p>
      <p class="g-pstyle4">with debt</p>
    </div>
    <div
      id="g-ai2-12"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:57.7638%;width:75px;"
    >
      <p class="g-pstyle4">Bachelors</p>
    </div>
    <div
      id="g-ai2-13"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:83.3613%;width:64px;"
    >
      <p class="g-pstyle4">Masters</p>
    </div>
  </div>

  <!-- Artboard: 620px -->
  <div
    id="g-620px"
    class="g-artboard"
    style="width:620px; height:370px;"
    data-aspect-ratio="1.676"
    data-min-width="620"
  >
    <div style=""></div>
    <img
      id="g-620px-img"
      class="g-aiImg"
      alt="A stacked bar chart showing the breakdown of net worth determined by five different simulations."
      src="images/millennials_bar/620px.png?v=13"
    />
    <div
      id="g-ai3-1"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:1.4617%;margin-top:-7.4px;left:23.6976%;width:121px;"
    >
      <p class="g-pstyle0">$10 million dollars</p>
    </div>
    <div
      id="g-ai3-2"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:4.1644%;margin-top:-6.4px;left:76.4855%;width:56px;"
    >
      <p class="g-pstyle1">Home</p>
    </div>
    <div
      id="g-ai3-3"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:10.3836%;margin-top:-12.4px;left:76.528%;width:92px;"
    >
      <p class="g-pstyle2">Taxable</p>
      <p class="g-pstyle2">investments</p>
    </div>
    <div
      id="g-ai3-4"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:16.5968%;margin-top:-7.4px;left:76.0768%;width:52px;"
    >
      <p class="g-pstyle3">401k</p>
    </div>
    <div
      id="g-ai3-5"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:19.2995%;margin-top:-7.4px;left:23.6976%;width:29px;"
    >
      <p class="g-pstyle0">8</p>
    </div>
    <div
      id="g-ai3-6"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:36.8671%;margin-top:-7.4px;left:23.6976%;width:29px;"
    >
      <p class="g-pstyle0">6</p>
    </div>
    <div
      id="g-ai3-7"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:54.4346%;margin-top:-7.4px;left:23.6976%;width:29px;"
    >
      <p class="g-pstyle0">4</p>
    </div>
    <div
      id="g-ai3-8"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:72.2725%;margin-top:-7.4px;left:23.6976%;width:29px;"
    >
      <p class="g-pstyle0">2</p>
    </div>
    <div
      id="g-ai3-9"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:89.8401%;margin-top:-7.4px;left:23.6976%;width:29px;"
    >
      <p class="g-pstyle0">0</p>
    </div>
    <div
      id="g-ai3-10"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:28.1828%;width:80px;"
    >
      <p class="g-pstyle4">No college</p>
    </div>
    <div
      id="g-ai3-11"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:96.3265%;margin-top:-13.4px;left:41.1409%;width:75px;"
    >
      <p class="g-pstyle4">Bachelors</p>
      <p class="g-pstyle4">with debt</p>
    </div>
    <div
      id="g-ai3-12"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:53.7206%;width:75px;"
    >
      <p class="g-pstyle4">Bachelors</p>
    </div>
    <div
      id="g-ai3-13"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:94.5698%;margin-top:-6.9px;left:67.2263%;width:64px;"
    >
      <p class="g-pstyle4">Masters</p>
    </div>
  </div>
</div>
<!-- End ai2html - 2024-08-08 10:04 -->

<style>
  #g-millennials_bar-box,
  #g-millennials_bar-box .g-artboard {
    margin: 0 auto;
  }
  #g-millennials_bar-box p {
    margin: 0;
  }
  #g-millennials_bar-box .g-aiAbs {
    position: absolute;
  }
  #g-millennials_bar-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
  }
  /* #g-millennials_bar-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	} */
  #g-millennials_bar-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-app_fallback {
    position: relative;
    overflow: hidden;
  }
  #g-app_fallback p {
    font-weight: 500;
    line-height: 20px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 15px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-app_fallback .g-pstyle0 {
    font-size: 18px;
  }
  #g-app_fallback .g-pstyle1 {
    font-weight: 700;
    color: rgb(118, 118, 118);
  }
  #g-app_fallback .g-pstyle2 {
    line-height: 14px;
    height: 14px;
    font-size: 12px;
  }
  #g-app_fallback .g-pstyle3 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 12px;
    text-align: right;
    color: rgb(0, 107, 228);
  }
  #g-app_fallback .g-pstyle4 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    font-size: 12px;
    text-align: right;
    color: rgb(0, 35, 75);
  }
  #g-app_fallback .g-pstyle5 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    font-size: 12px;
    text-align: right;
    color: rgb(80, 175, 204);
  }
  #g-app_fallback .g-pstyle6 {
    line-height: 13px;
    height: 13px;
    font-size: 12px;
  }
  #g-app_fallback .g-pstyle7 {
    line-height: 17px;
    font-size: 13px;
    color: rgb(114, 114, 114);
  }
  #g-300px {
    position: relative;
    overflow: hidden;
  }
  #g-300px p {
    font-weight: 500;
    line-height: 13px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-300px .g-pstyle0 {
    line-height: 14px;
    height: 14px;
  }
  #g-300px .g-pstyle1 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    text-align: right;
    color: rgb(0, 107, 228);
  }
  #g-300px .g-pstyle2 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    text-align: right;
    color: rgb(0, 35, 75);
  }
  #g-300px .g-pstyle3 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    text-align: right;
    color: rgb(80, 175, 204);
  }
  #g-300px .g-pstyle4 {
    height: 13px;
  }
  #g-355px {
    position: relative;
    overflow: hidden;
  }
  #g-355px p {
    font-weight: 500;
    line-height: 13px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-355px .g-pstyle0 {
    line-height: 14px;
    height: 14px;
  }
  #g-355px .g-pstyle1 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    text-align: right;
    color: rgb(0, 107, 228);
  }
  #g-355px .g-pstyle2 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    text-align: right;
    color: rgb(0, 35, 75);
  }
  #g-355px .g-pstyle3 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    text-align: right;
    color: rgb(80, 175, 204);
  }
  #g-355px .g-pstyle4 {
    height: 13px;
  }
  #g-620px {
    position: relative;
    overflow: hidden;
  }
  #g-620px p {
    font-weight: 500;
    line-height: 13px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(51, 51, 51);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-620px .g-pstyle0 {
    line-height: 14px;
    height: 14px;
  }
  #g-620px .g-pstyle1 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    color: rgb(0, 107, 228);
  }
  #g-620px .g-pstyle2 {
    font-weight: 700;
    line-height: 12px;
    height: 12px;
    color: rgb(0, 35, 75);
  }
  #g-620px .g-pstyle3 {
    font-weight: 700;
    line-height: 14px;
    height: 14px;
    color: rgb(80, 175, 204);
  }
  #g-620px .g-pstyle4 {
    height: 13px;
  }
</style>
