<!-- Generated by ai2html on 2024-08-15 14:25 -->
<!-- ai file: weatlth_gap.ai -->

<script>
  import { onMount } from "svelte";
  onMount(() => {
    (function (containerId, opts) {
      if (!("querySelector" in document)) return;
      var container = document.getElementById(containerId);
      var nameSpace = opts.namespace || "";
      var onResize = throttle(update, 200);
      var waiting = !!window.IntersectionObserver;
      var observer;
      update();

      document.addEventListener("DOMContentLoaded", update);
      window.addEventListener("resize", onResize);

      function update() {
        var artboards = selectChildren(
            "." + nameSpace + "artboard[data-min-width]",
            container
          ),
          width = Math.round(container.getBoundingClientRect().width);

        // Set artboard visibility based on container width
        artboards.forEach(function (el) {
          var minwidth = el.getAttribute("data-min-width"),
            maxwidth = el.getAttribute("data-max-width");
          if (+minwidth <= width && (+maxwidth >= width || maxwidth === null)) {
            if (!waiting) {
              selectChildren("." + nameSpace + "aiImg", el).forEach(
                updateImgSrc
              );
            }
            el.style.display = "block";
          } else {
            el.style.display = "none";
          }
        });

        // Initialize lazy loading on first call
        if (waiting && !observer) {
          if (elementInView(container)) {
            waiting = false;
            update();
          } else {
            observer = new IntersectionObserver(onIntersectionChange, {});
            observer.observe(container);
          }
        }
      }

      function elementInView(el) {
        var bounds = el.getBoundingClientRect();
        return bounds.top < window.innerHeight && bounds.bottom > 0;
      }

      // Replace blank placeholder image with actual image
      function updateImgSrc(img) {
        var src = img.getAttribute("data-src");
        if (src && img.getAttribute("src") != src) {
          img.setAttribute("src", src);
        }
      }

      function onIntersectionChange(entries) {
        // There may be multiple entries relating to the same container
        // (captured at different times)
        var isIntersecting = entries.reduce(function (memo, entry) {
          return memo || entry.isIntersecting;
        }, false);
        if (isIntersecting) {
          waiting = false;
          // update: don't remove -- we need the observer to trigger an update
          // when a hidden map becomes visible after user interaction
          // (e.g. when an accordion menu or tab opens)
          // observer.disconnect();
          // observer = null;
          update();
        }
      }

      function selectChildren(selector, parent) {
        return parent
          ? Array.prototype.slice.call(parent.querySelectorAll(selector))
          : [];
      }

      // based on underscore.js
      function throttle(func, wait) {
        var timeout = null,
          previous = 0;
        function run() {
          previous = Date.now();
          timeout = null;
          func();
        }
        return function () {
          var remaining = wait - (Date.now() - previous);
          if (remaining <= 0 || remaining > wait) {
            clearTimeout(timeout);
            run();
          } else if (!timeout) {
            timeout = setTimeout(run, remaining);
          }
        };
      }
    })("g-weatlth_gap-box", {
      namespace: "g-",
      setup: window.setupInteractive || window.getComponent,
    });
  });
</script>

<div id="g-weatlth_gap-box" class="ai2html">
  <!-- Artboard: 300px -->
  <div
    id="g-300px"
    class="g-artboard"
    style="max-width: 300px;max-height: 370px"
    data-aspect-ratio="0.811"
    data-min-width="0"
    data-max-width="354"
  >
    <div style="padding: 0 0 123.3333% 0;"></div>
    <img
      id="g-300px-img"
      class="g-aiImg"
      alt="A dot plot showing the median net worth of millennials is more than boomers at the same age, but that the wealth gap between the 80th and 20th percentiles is larger."
      data-src="images/weatlth_gap/300px.png?v=32"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="g-ai1-1"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:1.5876%;margin-top:-6.9px;left:0.0003%;width:119px;"
    >
      <p class="g-pstyle0">$350,000 net worth</p>
    </div>
    <div
      id="g-ai1-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:3.0833%;margin-top:-7.4px;left:69.5641%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle1">80th percentile</p>
    </div>
    <div
      id="g-ai1-3"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:14.2903%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">300,000</p>
    </div>
    <div
      id="g-ai1-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:29.786%;margin-top:-36.2px;left:17.6999%;width:99px;"
    >
      <p class="g-pstyle2">The median of</p>
      <p class="g-pstyle2">millennials are</p>
      <p class="g-pstyle2">doing better</p>
      <p class="g-pstyle2">than boomers</p>
      <p class="g-pstyle2">at their age ...</p>
    </div>
    <div
      id="g-ai1-5"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:26.7227%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">250,000</p>
    </div>
    <div
      id="g-ai1-6"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:39.1551%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">200,000</p>
    </div>
    <div
      id="g-ai1-7"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:51.8578%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">150,000</p>
    </div>
    <div
      id="g-ai1-8"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:60.1644%;margin-top:-14.6px;left:55.3975%;width:124px;"
    >
      <p class="g-pstyle2">... but the wealth</p>
      <p class="g-pstyle2">gap is much larger.</p>
    </div>
    <div
      id="g-ai1-9"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:64.2903%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">100,000</p>
    </div>
    <div
      id="g-ai1-10"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:76.7227%;margin-top:-6.9px;left:0.0003%;width:56px;"
    >
      <p class="g-pstyle0">50,000</p>
    </div>
    <div
      id="g-ai1-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:88.759%;margin-top:-7.4px;left:69.5641%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle1">20th percentile</p>
    </div>
    <div
      id="g-ai1-12"
      class="g-GFX g-aiAbs g-aiPointText"
      style="top:89.4254%;margin-top:-6.9px;left:0.0003%;width:28px;"
    >
      <p class="g-pstyle0">0</p>
    </div>
    <div
      id="g-ai1-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:95.7951%;margin-top:-14.4px;left:90.6875%;margin-left:-37px;width:74px;"
    >
      <p class="g-pstyle3">Baby</p>
      <p class="g-pstyle3">boomers</p>
    </div>
    <div
      id="g-ai1-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:95.7951%;margin-top:-8.4px;left:39.6084%;width:85px;"
    >
      <p class="g-pstyle4">Millennials</p>
    </div>
  </div>

  <!-- Artboard: 355px -->
  <div
    id="g-355px"
    class="g-artboard"
    style="width:355px; height:370px;"
    data-aspect-ratio="0.959"
    data-min-width="355"
    data-max-width="619"
  >
    <div style=""></div>
    <img
      id="g-355px-img"
      class="g-aiImg"
      alt="A dot plot showing the median net worth of millennials is more than boomers at the same age, but that the wealth gap between the 80th and 20th percentiles is larger."
      data-src="images/weatlth_gap/355px.png?v=32"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="g-ai2-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.5876%;margin-top:-6.9px;left:0.0003%;width:119px;"
    >
      <p class="g-pstyle0">$350,000 net worth</p>
    </div>
    <div
      id="g-ai2-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:3.0833%;margin-top:-7.4px;left:66.7028%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle1">80th percentile</p>
    </div>
    <div
      id="g-ai2-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.2903%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">300,000</p>
    </div>
    <div
      id="g-ai2-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:29.786%;margin-top:-36.2px;left:19.0331%;width:99px;"
    >
      <p class="g-pstyle2">The median of</p>
      <p class="g-pstyle2">millennials are</p>
      <p class="g-pstyle2">doing better</p>
      <p class="g-pstyle2">than boomers</p>
      <p class="g-pstyle2">at their age ...</p>
    </div>
    <div
      id="g-ai2-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:26.7227%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">250,000</p>
    </div>
    <div
      id="g-ai2-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:39.1551%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">200,000</p>
    </div>
    <div
      id="g-ai2-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:51.8578%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">150,000</p>
    </div>
    <div
      id="g-ai2-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:60.1644%;margin-top:-14.6px;left:55.2944%;width:124px;"
    >
      <p class="g-pstyle2">... but the wealth</p>
      <p class="g-pstyle2">gap is much larger.</p>
    </div>
    <div
      id="g-ai2-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:64.2903%;margin-top:-6.9px;left:0.0003%;width:63px;"
    >
      <p class="g-pstyle0">100,000</p>
    </div>
    <div
      id="g-ai2-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:76.7227%;margin-top:-6.9px;left:0.0003%;width:56px;"
    >
      <p class="g-pstyle0">50,000</p>
    </div>
    <div
      id="g-ai2-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:88.759%;margin-top:-7.4px;left:66.7028%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle1">20th percentile</p>
    </div>
    <div
      id="g-ai2-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:89.4254%;margin-top:-6.9px;left:0.0003%;width:28px;"
    >
      <p class="g-pstyle0">0</p>
    </div>
    <div
      id="g-ai2-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:95.7951%;margin-top:-14.4px;left:90.6795%;margin-left:-37px;width:74px;"
    >
      <p class="g-pstyle3">Baby</p>
      <p class="g-pstyle3">boomers</p>
    </div>
    <div
      id="g-ai2-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:95.7951%;margin-top:-8.4px;left:42.05%;width:85px;"
    >
      <p class="g-pstyle4">Millennials</p>
    </div>
  </div>

  <!-- Artboard: 620px -->
  <div
    id="g-620px"
    class="g-artboard"
    style="width:620px; height:370px;"
    data-aspect-ratio="1.676"
    data-min-width="620"
  >
    <div style=""></div>
    <img
      id="g-620px-img"
      class="g-aiImg"
      alt="A dot plot showing the median net worth of millennials is more than boomers at the same age, but that the wealth gap between the 80th and 20th percentiles is larger."
      data-src="images/weatlth_gap/620px.png?v=32"
      src="data:image/gif;base64,R0lGODlhCgAKAIAAAB8fHwAAACH5BAEAAAAALAAAAAAKAAoAAAIIhI+py+0PYysAOw=="
    />
    <div
      id="g-ai3-1"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:1.4617%;margin-top:-7.4px;left:-0.0001%;width:127px;"
    >
      <p class="g-pstyle0">$350,000 net worth</p>
    </div>
    <div
      id="g-ai3-2"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:3.0833%;margin-top:-7.4px;left:63.8171%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle1">80th percentile</p>
    </div>
    <div
      id="g-ai3-3"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:14.1644%;margin-top:-7.4px;left:-0.0001%;width:66px;"
    >
      <p class="g-pstyle0">300,000</p>
    </div>
    <div
      id="g-ai3-4"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:26.5968%;margin-top:-7.4px;left:-0.0001%;width:66px;"
    >
      <p class="g-pstyle0">250,000</p>
    </div>
    <div
      id="g-ai3-5"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:34.4259%;margin-top:-17.4px;left:14.424%;width:245px;"
    >
      <p class="g-pstyle2">The median of millennials are doing</p>
      <p class="g-pstyle2">better than boomers at their age ...</p>
    </div>
    <div
      id="g-ai3-6"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:39.0292%;margin-top:-7.4px;left:-0.0001%;width:66px;"
    >
      <p class="g-pstyle0">200,000</p>
    </div>
    <div
      id="g-ai3-7"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:51.7319%;margin-top:-7.4px;left:-0.0001%;width:66px;"
    >
      <p class="g-pstyle0">150,000</p>
    </div>
    <div
      id="g-ai3-8"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:59.0205%;margin-top:-17.4px;left:60.1856%;width:141px;"
    >
      <p class="g-pstyle2">... but the wealth</p>
      <p class="g-pstyle2">gap is much larger.</p>
    </div>
    <div
      id="g-ai3-9"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:64.1644%;margin-top:-7.4px;left:-0.0001%;width:66px;"
    >
      <p class="g-pstyle0">100,000</p>
    </div>
    <div
      id="g-ai3-10"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:76.8671%;margin-top:-7.4px;left:-0.0001%;width:59px;"
    >
      <p class="g-pstyle0">50,000</p>
    </div>
    <div
      id="g-ai3-11"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:88.759%;margin-top:-7.4px;left:64.0739%;margin-left:-51.5px;width:103px;"
    >
      <p class="g-pstyle1">20th percentile</p>
    </div>
    <div
      id="g-ai3-12"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:89.2995%;margin-top:-7.4px;left:-0.0001%;width:29px;"
    >
      <p class="g-pstyle0">0</p>
    </div>
    <div
      id="g-ai3-13"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:96.0746%;margin-top:-15.5px;left:90.6627%;margin-left:-39px;width:78px;"
    >
      <p class="g-pstyle3">Baby</p>
      <p class="g-pstyle3">boomers</p>
    </div>
    <div
      id="g-ai3-14"
      class="g-shadow-text g-aiAbs g-aiPointText"
      style="top:95.6692%;margin-top:-9px;left:49.084%;width:89px;"
    >
      <p class="g-pstyle2">Millennials</p>
    </div>
  </div>
</div>
<!-- End ai2html - 2024-08-15 14:25 -->

<style>
  #g-weatlth_gap-box,
  #g-weatlth_gap-box .g-artboard {
    margin: 0 auto;
  }
  #g-weatlth_gap-box p {
    margin: 0;
  }
  #g-weatlth_gap-box .g-aiAbs {
    position: absolute;
  }
  #g-weatlth_gap-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
  }
  /* #g-weatlth_gap-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	} */
  #g-weatlth_gap-box .g-aiPointText p {
    white-space: nowrap;
  }
  #g-300px {
    position: relative;
    overflow: hidden;
  }
  #g-300px p {
    font-weight: 500;
    line-height: 14px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(50, 50, 50);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-300px .g-pstyle0 {
    line-height: 13px;
    height: 13px;
    font-size: 11px;
  }
  #g-300px .g-pstyle1 {
    height: 14px;
    text-align: center;
  }
  #g-300px .g-pstyle2 {
    height: 14px;
  }
  #g-300px .g-pstyle3 {
    height: 14px;
    font-size: 13px;
    text-align: center;
  }
  #g-300px .g-pstyle4 {
    line-height: 16px;
    height: 16px;
    font-size: 13px;
  }
  #g-355px {
    position: relative;
    overflow: hidden;
  }
  #g-355px p {
    font-weight: 500;
    line-height: 14px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(50, 50, 50);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-355px .g-pstyle0 {
    line-height: 13px;
    height: 13px;
    font-size: 11px;
  }
  #g-355px .g-pstyle1 {
    height: 14px;
    text-align: center;
  }
  #g-355px .g-pstyle2 {
    height: 14px;
  }
  #g-355px .g-pstyle3 {
    height: 14px;
    font-size: 13px;
    text-align: center;
  }
  #g-355px .g-pstyle4 {
    line-height: 16px;
    height: 16px;
    font-size: 13px;
  }
  #g-620px {
    position: relative;
    overflow: hidden;
  }
  #g-620px p {
    font-weight: 500;
    line-height: 17px;
    height: auto;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 14px;
    text-align: left;
    color: rgb(50, 50, 50);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    position: static;
  }
  #g-620px .g-pstyle0 {
    line-height: 14px;
    height: 14px;
    font-size: 12px;
  }
  #g-620px .g-pstyle1 {
    line-height: 14px;
    height: 14px;
    font-size: 12px;
    text-align: center;
  }
  #g-620px .g-pstyle2 {
    height: 17px;
  }
  #g-620px .g-pstyle3 {
    line-height: 15px;
    height: 15px;
    text-align: center;
  }

  /* Custom CSS */
  .g-shadow-text {
    background-color: white;
  }
</style>
